const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Henri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../.sites-artifacts/release112-endgame/dist/client/game');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(8799,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8799/');await page.waitForFunction('runtimeAssetsReady',{},{timeout:120000});
 await page.evaluate(`startTitleGame(false);runCurrentTurn=()=>{};state.gameMode='hallBattles';state.party=['Glimmer','Torren','Verseborn'];state.activeParty=state.party;const ref=addOwnedGear('Sanctuary Dynamo',1,{rarity:'Artifact',stats:gearByName('Sanctuary Dynamo').stats,separateCopy:true})[0];baseJobs.Torren.gear.armour=ref;`);
 for(let stage=51;stage<=60;stage++){
  await page.evaluate(stage=>{const info=hallBattleInfo(stage);state.party.forEach(id=>{baseJobs[id].hp=0;baseJobs[id].mp=0;});state.map=info.mapId;startBattle(info.name,hallEnemiesForStage(stage,info.waves[1],2),undefined,null,[],{hallBoss:true});battle.hallStage=stage;battle.phaseTotal=3;battle.waves=[];battle.resolving=true;updateBossMechanicDisplay();},stage);
  const result=await page.evaluate(()=>{const boss=battle.enemies.find(e=>e.endgameBoss),old=drawCombatRoleIcon,calls=[];drawCombatRoleIcon=(...args)=>calls.push(args);try{drawBattleScene();const [x,y]=enemyBattlePosition(battle.enemies.indexOf(boss)),others=battle.enemies.filter(e=>e!==boss).map(e=>enemyBattlePosition(battle.enemies.indexOf(e)));return {roles:calls.length,domRoles:document.querySelectorAll('.boss-roster-role').length,units:battle.party.length+battle.enemies.length,title:document.querySelector('.boss-mechanic-panel strong').textContent,name:boss.name,front:others.every(p=>p[0]>x)&&y===131,scale:enemyBattleScale(enemyAnimationKey(boss)),full:battle.party.every(u=>u.hp===totals(u.id).max&&u.mp===totals(u.id).mp&&!u.down),bossBanner:document.querySelector('.boss-mechanic-panel').classList.contains('is-boss')};}finally{drawCombatRoleIcon=old;}});
  assert.equal(result.roles,0);assert.equal(result.domRoles,result.units);assert.equal(result.title,result.name);assert.ok(result.front&&result.full&&result.bossBanner);assert.equal(result.scale,1.12);
 }
 for(const width of [1440,593,390]){
  await page.setViewportSize({width,height:1000});await page.waitForTimeout(150);
  const bounds=await page.evaluate(()=>{const panel=document.querySelector('.boss-mechanic-panel').getBoundingClientRect(),p=document.querySelector('.boss-mechanic-panel p').getBoundingClientRect(),canvas=document.querySelector('canvas').getBoundingClientRect(),rosters=[...document.querySelectorAll('.boss-hud-roster')].map(el=>el.getBoundingClientRect());return {left:(p.left-panel.left)/panel.width,right:(panel.right-p.right)/panel.width,top:(p.top-panel.top)/panel.height,above:rosters.every(r=>r.bottom<=canvas.top),asset:getComputedStyle(document.querySelector('.boss-mechanic-panel')).backgroundImage};});
  assert.ok(bounds.left>=.539&&bounds.right>=.119&&bounds.top>=.33&&bounds.above&&bounds.asset.includes('warning-banner'));await page.screenshot({path:path.resolve(__dirname,'../.sites-artifacts/boss-banner-'+width+'.png')});
 }
 assert.deepEqual(errors,[]);console.log('PASS 10 red boss banners, HP/role rosters outside combat, larger centered frontline bosses, full HP/MP after gear changes, desktop/593px/mobile');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
