const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Henri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../.sites-artifacts/release112-endgame/dist/client/game');
const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]);const file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(8799,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],missing=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()===404&&!r.url().includes('favicon'))missing.push(r.url());});
 await page.goto('http://127.0.0.1:8799/');await page.waitForFunction('runtimeAssetsReady',{},{timeout:120000});
 await page.evaluate('runCurrentTurn = () => {}');
 const loaded=await page.evaluate(`Object.keys(enemyAnimationFiles).map(name=>({name,ready:Boolean(enemyAnimationSheets[enemyAnimationFiles[name]])}))`);assert.ok(loaded.every(e=>e.ready),JSON.stringify({failed:loaded.filter(e=>!e.ready),missing,errors}));
 assert.equal(await page.evaluate('Object.keys(endgameBossVfxSheets).length'),10);
 const compatibility=await page.evaluate(`(()=>{startTitleGame(false);state.gameMode='hallBattles';state.party=['Verseborn','Torren','Glimmer'];state.activeParty=state.party;state.gold=8765;state.hallBattles={clearedStages:Array.from({length:50},(_,i)=>i+1),unlockedStage:50,shopStage:50,shopOffers:{}};const before=JSON.stringify({party:state.party,gear:state.gear,inventory:state.inventory,gold:state.gold});saveGame(hallSaveKey());loadGame(hallSaveKey());return hallBattleProgress().unlockedStage===51&&before===JSON.stringify({party:state.party,gear:state.gear,inventory:state.inventory,gold:state.gold});})()`);assert.ok(compatibility);
 for(let stage=1;stage<=60;stage++){
  const ready=await page.evaluate(s=>{const info=hallBattleInfo(s);return [info.enemies,...info.waves].every((keys,i)=>hallEnemiesForStage(s,keys,i).every(e=>Boolean(enemyAnimationSheetFor(e))));},stage);assert.ok(ready,'Stage '+stage);
 }
 for(let stage=51;stage<=60;stage++){
  await page.evaluate(s=>{const info=hallBattleInfo(s);state.map=info.mapId;startBattle('Hall '+s+'/60 - '+info.name+' - Phase 3/3',hallEnemiesForStage(s,info.waves[1],2),undefined,null,[],{hallBoss:true,roundCap:60});battle.hallStage=s;battle.phaseTotal=3;battle.resolving=true;battle.enemies.forEach(e=>{if(e.endgameBoss)endgameMechanicState(e);});updatePanels();},stage);
  await page.waitForTimeout(160);await page.screenshot({path:path.resolve(__dirname,'../.sites-artifacts/battle-'+stage+'.png')});
  const rectangles=await page.evaluate(()=>{const boss=battle.enemies.find(e=>e.endgameBoss),original=ctx.fillRect;let count=0;ctx.fillRect=function(){count++;};try{for(const kind of ['melee','magic','ultimate','buff','heal','utility']){effect=makeEnemyBattleEffect(boss,battle.party[0],{kind,name:'Transparency check'});for(let tick=0;tick<200&&effect;tick++)drawEffect();}}finally{ctx.fillRect=original;effect=null;}return count;});assert.equal(rectangles,0,'Opaque fallback on Stage '+stage);
  const samples=await page.evaluate(()=>{const boss=battle.enemies.find(e=>e.endgameBoss),image=ctx.drawImage,rows=[];try{ctx.drawImage=function(...args){rows.push([args[1],args[2],args[7],args[8]]);};for(const kind of ['melee','buff','magic','ultimate']){const fx=makeEnemyBattleEffect(boss,kind==='buff'?battle.enemies[1]:battle.party[0],{kind,name:'Row test'});for(const time of [0,.4,.8,1]){fx.startedAt=performance.now()-fx.timing.impactMs*time;drawEndgameBossVfx(fx);}if(kind==='magic'&&!(fx.fromX>fx.toX))throw Error('Wrong projectile direction');if(kind==='buff'){const [x]=enemyBattlePosition(1,battle.enemies.length);if(fx.vfxTargets[0].x!==x)throw Error('Wrong support target');}}}finally{ctx.drawImage=image;}return rows;});assert.equal(samples.length,16);assert.ok(samples.every(s=>s[2]>0&&s[3]>0));
  for(const kind of ['melee','buff','magic','ultimate']){
   const timing=await page.evaluate(kind=>{const boss=battle.enemies.find(e=>e.endgameBoss);battle.party.forEach(u=>{u.hp=u.max=50000;u.baseEvasion=0;});const original=chooseEnemyAction;chooseEnemyAction=unit=>kind==='buff'?{kind:'buff',name:'Support visual check',target:battle.enemies[1],buffs:[{type:'defenseUp',duration:2,value:.1}]}:enemyActionForKind(unit,kind);battle.resolving=true;try{resolveEnemyTurn({side:'enemy',index:battle.enemies.indexOf(boss)},'');}finally{chooseEnemyAction=original;}return effect.timing;},kind);
   await page.waitForTimeout(timing.impactMs+15);await page.screenshot({path:path.resolve(__dirname,'../.sites-artifacts/action-'+stage+'-'+kind+'.png')});
   await page.waitForTimeout(timing.totalMs-timing.impactMs+250);assert.equal(await page.evaluate('effect===null'),true,'Effect did not expire '+stage+' '+kind);
  }
 }
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);await page.screenshot({path:path.resolve(__dirname,'../.sites-artifacts/endgame-narrow.png')});
 const hud=await page.locator('#bossMechanicHud').boundingBox(),canvas=await page.locator('canvas').first().boundingBox();assert.ok(hud&&canvas&&hud.y+hud.height<=canvas.y+2,'HUD overlaps battlefield');
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log(JSON.stringify({loaded:loaded.length,bossVfx:10,battleActions:40,stages:60,stage50Save:compatibility,errors,missing}));
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
