const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Henri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,process.argv.includes('--runtime')?'../dist/client/game':'../public/game');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(8807,'127.0.0.1',r));let browser;try{
browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8807/');await page.waitForFunction('runtimeAssetsReady',{},{timeout:120000});
await page.evaluate(`startTitleGame(false);state.gameMode='hallBattles';mode='walk';toggleMenu();menuTab='lore';renderMenu();`);
await page.evaluate(`state.inventory={"Marla's Soup":2,"Clockwork Tonic":2,"Phoenix Ticket":2};menuTab='items';renderMenu();`);
assert.equal(await page.locator('.selection-row .resource-hp').count(),1);
assert.equal(await page.locator('.selection-row .resource-mp').count(),1);
assert.equal(await page.locator('.selection-row .resource-revive').count(),1);
assert.ok(await page.locator('.selection-row .resource-revive').innerText().then(t=>t==='REVIVE'));
const sheetUrl=await page.locator('.selection-row .resource-hp').evaluate(e=>getComputedStyle(e).backgroundImage.match(/url\("?(.*?)"?\)/)[1]);
assert.ok(await page.evaluate(async url=>{const img=new Image();img.src=url;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);return ctx.getImageData(0,0,c.width,c.height).data.some((v,i)=>i%4===3&&v>0);},sheetUrl));
await page.screenshot({path:path.resolve(__dirname,'../.sites-artifacts/item-icons.png')});
await page.evaluate(`menuTab='lore';renderMenu();`);
await page.locator('[data-lexicon-stage]').selectOption('60');assert.ok(await page.locator('.hall-archive').innerText().then(t=>t.includes('Ilyss')));
assert.equal(await page.getByRole('heading',{name:'Issue Chronicle',exact:true}).count(),0);
assert.equal(await page.getByRole('heading',{name:'Rare & Miniboss Field Notes',exact:true}).count(),0);
await page.evaluate(`const p=progressFor('Verseborn');p.rank0=rank0Choices.Verseborn[0].name;p.talents=[];selectedSkillHero='Verseborn';menuTab='skills';renderMenu();`);
assert.ok(await page.locator('[data-reset-talents]').isEnabled());
await page.locator('[data-reset-talents]').click();
assert.equal(await page.evaluate(`progressFor('Verseborn').rank0 || null`),null);
await page.locator('[data-rank0]').nth(1).click();
assert.equal(await page.evaluate(`progressFor('Verseborn').rank0`),await page.evaluate(`rank0Choices.Verseborn[1].name`));
await page.evaluate(`menuTab='lore';renderMenu();`);
await page.screenshot({path:path.resolve(__dirname,'../.sites-artifacts/archive-lore.png')});
await page.evaluate(`menuTab='world';renderMenu();`);assert.ok(await page.locator('.archive-legend-item').count()>30);
assert.ok(await page.locator('[data-tab="quests"]').isHidden());
assert.equal(await page.locator('[data-tab="world"]').innerText(),'Combat Guide');
assert.equal(await page.locator('[data-tab="lore"]').innerText(),'Bestiary');
assert.equal(await page.locator('.world-grid').count(),0);
await page.screenshot({path:path.resolve(__dirname,'../.sites-artifacts/archive-world.png')});
await page.evaluate(`menuTab='system';renderMenu();`);
assert.equal(await page.locator('.battle-report-exports').count(),1);
assert.equal(await page.locator('.postgame-panel').count(),0);
assert.equal(await page.locator('.hall-save-exports').count(),1);
await page.evaluate(`menuTab='developer';renderMenu();`);
assert.equal(await page.locator('.battle-report-exports').count(),0);
await page.evaluate(`state.gameMode='story';menuTab='world';renderMenu();`);
assert.ok(await page.locator('[data-tab="quests"]').isVisible());
assert.equal(await page.locator('[data-tab="world"]').innerText(),'World');
assert.equal(await page.locator('.world-grid').count(),1);
await page.evaluate(`state.gameMode='hallBattles';mode='battle';battle={hallStage:5,enemies:[],party:[],waves:[],phaseTotal:1};for(let i=0;i<20;i++)updateBossMechanicDisplay();`);
assert.ok(await page.locator('#bossMechanicHud').isHidden());
assert.equal(await page.locator('.game').evaluate(e=>getComputedStyle(e).paddingTop),'0px');
await page.evaluate(`battle.mechanicAnnouncement={title:'Foreman Orders',text:'Brace for the next attack.',until:performance.now()+60000};updateBossMechanicDisplay();`);
assert.ok(await page.locator('#bossMechanicHud').isVisible());
assert.equal(await page.locator('.game').evaluate(e=>getComputedStyle(e).paddingTop),'146px');
await page.evaluate(`delete battle.mechanicAnnouncement;for(let i=0;i<20;i++)updateBossMechanicDisplay();mode='walk';battle=null;`);
assert.equal(await page.locator('.game').evaluate(e=>getComputedStyle(e).paddingTop),'0px');
assert.deepEqual(errors,[]);console.log('PASS Lore stage selection and World icon legend in browser');
if(process.argv.includes('--runtime')) {
  assert.ok(await page.evaluate(`enemyAnimationSheets['Ash Wyrm'].image.complete && new Set(enemyAnimationSheets['Ash Wyrm'].frameSequences.idle).size===5`));
  await page.evaluate(`el.menu.classList.add('hidden');hallBattleProgress().unlockedStage=54;startHallBattleStage(54);drawBattleScene();`);
  await page.screenshot({path:path.resolve(__dirname,'../.sites-artifacts/classic-ash-wyrm.png')});
  assert.deepEqual(errors,[]);
}
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
