const fs = require('node:fs');
const path = require('node:path');
const prefix = fs.readFileSync(__dirname + '/test_combat.cjs', 'utf8').split("run('runQaChecks()');")[0]
  .replace('sandbox.window = sandbox;', 'sandbox.fetch=async()=>({ok:false});sandbox.window = sandbox;');
const {run} = new Function('require','__dirname',prefix+';return {run};')(require,__dirname);
const data = JSON.parse(run(`JSON.stringify(Array.from({length:10},(_,i)=>{const stage=51+i,info=hallBattleInfo(stage);return {stage,name:info.name,phases:[info.enemies,...info.waves].map((keys,phase)=>({phase:phase+1,rhythm:ENDGAME_STAGE_RHYTHMS[stage]?.[phase]||null,enemies:hallEnemiesForStage(stage,keys,phase).map(unit=>({name:unit.name,mechanic:unit.endgameBoss,moves:enemyAbilityProfile(unit)?.moves||{},cycle:enemyAbilityProfile(unit)?.cycle||[]}))}))};}))`));
const rotations = {
  51:['Sentinel: Reception Combination voorbereiden (geen damage) -> gerichte impact -> opnieuw voorbereiden. Seal Bearer beschermt hem tijdens voorbereiding.','Thaddeus: voorbereiden -> impact. Reginald beschermt de spreker; Custodian healt gewonde allies of cleanset waar zijn kit dat toestaat.','Veyr: ontbrekende Protected Guest aanwijzen -> Last Courtesy voorbereiden -> gerichte impact. Break verwijdert de bescherming en opent een 30% direct-damage venster. AoE op de gast wordt verzwakt, zonder rebuke.'],
  52:['Gewonde Clergy: Prayer voorbereiden -> heal op de meest gewonde ally -> offensieve herstelactie. Justin beschermt de healer tijdens voorbereiding.','Gewonde Lysra: dezelfde herstelcyclus. Seal Bearer versterkt de heal; Justin maakt cleanse mogelijk.','Gewonde Maelin: tijdelijke wards + Renewal voorbereiden -> party-heal -> offensieve herstelactie. Silence/Break annuleert de voorbereiding, verwijdert haar wards en geeft haar 25% magic vulnerability. Geen herstelritueel wanneer niemand voldoende gewond is of haar MP ontoereikend is.'],
  53:['Auditor: Assessment voorbereiden -> gerichte impact -> melee-herstelactie. Custodian ondersteunt herstel/cleanse.','Thaddeus: Sentence voorbereiden -> impact -> herstelactie. Escorts beschermen hem tijdens voorbereiding.','Voss roteert No repeated skills / No buffs / No magic / Designated target first. Stamps verhogen de straf; 2 stamps geven defense reduction en buff removal, 3 geven Silence. Bij actieve order en de juiste actiepositie: Final Notice voorbereiden -> impact -> herstelactie.'],
  54:['Wyrm: mark + Crossfire voorbereiden -> impact -> herstelactie. Pillar bouwt Break op het target.','Plumpin: mark + Falling Star voorbereiden -> impact -> herstelactie. Companions versterken de impact.','Guide: Guidance Mark -> eventueel eenmaal verplaatsen -> Astral Impact. Cleanse wist de pending aanval; controle onderbreekt. Companions richten fysieke Break-druk op het gemarkeerde target.'],
  55:['Gorg: Root Bind + Rootline Impact voorbereiden -> impact -> herstelactie. Pillar bouwt Break.','Plumpin: Root Bind + Memory Bloom voorbereiden -> impact -> herstelactie.','Guardian: Memory Adaptation op herhaalde aanvalscategorie. Root Eruption wordt op vaste actieposities voorbereid, veroorzaakt AoE met kans op roots en opent de Core. Native Core-acties en Break kunnen de Core ook openen. Core: +60% incoming damage.'],
  56:['Tja: mark + Strange Duet voorbereiden -> impact -> herstelactie. Tibby versterkt de combinatie.','Jory: mark + Borrowed Refrain voorbereiden -> impact -> herstelactie. Lysra kan healen; Nyx ondersteunt de druk.','Malkhius: Echo Sigil kopieert een sterke buff (of MAG +20% als niets beschikbaar is) -> occult mark -> delayed echo. Een pending echo heeft voorrang. Cleanse van de mark voorkomt de delayed echo. Companions buffen afwisselend zijn MAG.'],
  57:['Shade: Beguiling Veil + Dream Pursuit voorbereiden -> impact -> herstelactie.','Thaddeus: Beguiling Veil + False Testimony voorbereiden -> impact -> herstelactie. Beide companions kunnen met beschikbare heals ondersteunen.','Morvanna: Veil -> buff inversion -> Dream Collapse voorbereiden -> gerichte impact -> herstelactie. Veil op het slachtoffer versterkt Collapse; cleanse voorkomt die bonus. Native magic kan Sleep toepassen.'],
  58:['Brokk: Iron Double Impact voorbereiden -> Break-impact -> herstelactie. Pillar bouwt extra Break.','Grumm: Oathbound Assault voorbereiden -> impact -> herstelactie. Escorts beschermen hem.','Koru-Vak: Oathguard trekt single-target attacks naar hem; Chained Judgment wordt voorbereid -> Break-impact -> herstelactie. Break annuleert voorbereiding en opent Broken Oath (+75% incoming damage). Na het venster keert een sterker schild terug.'],
  59:['Jory: Opening Chorus voorbereiden -> impact -> herstelactie. Tja versterkt de impact.','Jory: Sanctified Chorus voorbereiden -> impact -> herstelactie. Lysra/Justin kunnen healen.','Selyra: rings opbouwen, afgewisseld met magic -> Crescendo aankondigen -> Grand Crescendo. Rings versterken damage; controle annuleert charging en rings. Gedode of gecontroleerde supports verlagen de ringcapaciteit. Companions buffen/healen waar mogelijk.'],
  60:['Thaddeus: Sealed Record voorbereiden -> impact -> herstelactie. Auditor en Custodian gebruiken hun bestaande rotation-pressure en herstelkits.','Maeric: Royal Execution voorbereiden -> impact -> herstelactie. Lucan en Sentinel beschermen hem tijdens voorbereiding.','Ilyss: Buff / Skill / Memory Record afwisselen -> opgeslagen effect reproduceren, met magic op iedere derde actiepositie. Buff Record neemt een buff weg; Skill Record blokkeert tijdelijk een recent skill; Memory Record bewaart een recent effect. Controle wist het record voordat het wordt gereproduceerd.']
};
let out='# Ember Hall 51-60: abilities en rotaties (release 126)\n\nDit overzicht is uit de actuele definities gegenereerd. Het repertoire is niet hetzelfde als een gegarandeerde rotatie: stage-specifieke acties hebben voorrang op de standaard AI. Controle, HP, MP, Resonance en levende companions veranderen keuzes.\n\nVoorbereidingsacties doen geen damage; de huidige algemene animatie kan wel een aanval naar een party-lid suggereren. De Sentinel gebruikt zijn normale aanvallen wanneer zijn speciale stage-rol niet actief is.\n';
for(const stage of data){
 out+=`\n## ${stage.stage} - ${stage.name}\n`;
 for(const phase of stage.phases){
  out+=`\n### Fase ${phase.phase}\n\n${rotations[stage.stage][phase.phase-1]}\n`;
  if(phase.rhythm)out+=`\nTegenreactie: ${phase.rhythm.hint}\nMark/status: ${phase.rhythm.status}. Cleanse van deze status annuleert de speciale gerichte impact. Onderbreken opent 20% physical en magic vulnerability voor 2 acties.\n`;
  for(const enemy of phase.enemies){
   out+=`\n#### ${enemy.name}: beschikbaar basisrepertoire\n\n| Ability | Type | Element | Basis MP | Effectdefinitie |\n|---|---|---|---:|---|\n`;
   for(const move of Object.values(enemy.moves)){
    const {name,kind,element,mpCost,...effects}=move;
    out+=`| ${name} | ${kind} | ${element} | ${mpCost||0} | ${JSON.stringify(effects).replaceAll('|','/')} |\n`;
   }
  }
 }
}
out+='\n## Leeshulp effectdefinities\n\ncoefficient = damagefactor van de scaling stat; healCoefficient = healingfactor. allTargets = AoE; allAllies = party-effect. buffs/status/extraStatuses geven type, waarde, duur en eventuele kans. chance 0.7 betekent 70%; value 0.25 betekent doorgaans 25%. healing = herstel, cleanse = een verwijderbaar negatief effect verwijderen, dispel = buff verwijderen. breakPower bepaalt extra Break-opbouw. Basis MP kan door efficiency/developer-instellingen wijzigen. Damage bevat ook level, buffs, resistances, crit, Guard en developer-instellingen.\n';
const destination=path.resolve(__dirname,'../ENDGAME_ABILITIES_126.md');
fs.writeFileSync(destination,out);console.log(destination);
