const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const assert = require('node:assert/strict');

// Exercise the actual game code without a browser, network, audio or a player's save.
const noop = () => {};
const drawing = new Proxy({}, { get: (target, key) => target[key] || (key === 'measureText' ? text => ({ width: String(text).length * 3 }) : noop) });
class Element {
  constructor() { this.children = []; this.dataset = {}; this.style = {}; this.attrs = {}; this._html = ''; this.classList = { add: noop, remove: noop, toggle: noop, contains: () => false }; }
  set innerHTML(value) { this._html = value; this.children = []; }
  get innerHTML() { return this._html; }
  getContext() { return drawing; }
  getBoundingClientRect() { return { width: 768, height: 672, left: 0, top: 0 }; }
  addEventListener() {}
  appendChild(child) { this.children.push(child); }
  querySelector() { return new Element(); }
  querySelectorAll() { return []; }
  setAttribute(key, value) { this.attrs[key] = value; }
  getAttribute(key) { return this.attrs[key]; }
  insertAdjacentHTML(where, value) { this._html = where === 'afterbegin' ? value + this._html : this._html + value; }
  focus() {}
}
const elements = new Map();
const body = new Element();
const document = { body, getElementById(id) { if (!elements.has(id)) elements.set(id, new Element()); return elements.get(id); }, querySelector: () => new Element(), querySelectorAll: () => [], createElement: () => new Element(), addEventListener: noop };
const storage = new Map();
const timers = [];
const sandbox = {
  console, document, URLSearchParams, structuredClone, location: { search: '?qa=full' }, performance: { now: () => 0 },
  Image: class { constructor() { this.complete = false; } addEventListener() {} },
  Audio: class { constructor(src) { this.src = src; this.paused = true; } addEventListener() {} pause() { this.paused = true; } play() { this.paused = false; return Promise.resolve(); } },
  ResizeObserver: class { observe() {} },
  requestAnimationFrame: noop, setTimeout: fn => { timers.push(fn); return timers.length; }, clearTimeout: noop,
  localStorage: { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value), removeItem: key => storage.delete(key) },
  navigator: {}, addEventListener: noop, devicePixelRatio: 1, innerWidth: 1000, innerHeight: 900,
};
sandbox.window = sandbox;
sandbox.__impact = () => timers.at(-1)();
vm.createContext(sandbox);
const gamePath = path.join(__dirname, '../public/game/game.js');
const htmlSource = fs.readFileSync(path.join(__dirname, '../public/game/index.html'), 'utf8');
const cssSource = fs.readFileSync(path.join(__dirname, '../public/game/styles.css'), 'utf8');
const gameSource = fs.readFileSync(gamePath, 'utf8');
vm.runInContext(gameSource, sandbox, { filename: gamePath });
const run = code => vm.runInContext(code, sandbox);
run('runQaChecks()');
const legacy = JSON.parse(body.getAttribute('data-qa-result'));
console.log(`Existing QA: ${legacy.passed}/${legacy.total}`);
for (const [name, result] of Object.entries(legacy.results)) if (!result.pass) console.error(name, result.detail);
assert.equal(legacy.passed, legacy.total);

let passed = 0;
function check(name, code) {
  assert.ok(run(code), name);
  passed++;
  console.log('PASS', name);
}
check('Every Flameguard tree has five tiers and fifteen choices', 'Object.keys(baseJobs).every(id => talentTrees[id].length===15 && [1,2,3,4,5].every(tier => talentTrees[id].filter(t=>t.tier===tier).length===3))');
check('Talent point levels match the ten-point progression', 'JSON.stringify(TALENT_POINT_LEVELS)===JSON.stringify([4,8,12,16,20,24,28,32,36,40])');
check('Every talent has a meaningful description', 'Object.values(talentTrees).flat().every(t => t.unlockDesc.length >= 8)');
check('All non-Ultimate skills store fixed costs', 'Object.values(baseJobs).flatMap(h=>h.skills).concat(Object.values(talentTrees).flat().filter(t=>t.type==="newSkill").map(t=>t.value),Object.values(TRANSFORMED_SKILLS).flat()).every(sk=>Number.isFinite(sk.cost) && !("mpRate" in sk))');
check('Increasing MAG increases Max MP without changing stored skill cost', `(() => {const old=baseJobs.Kael.stats.mag; const sk=baseJobs.Kael.skills.find(s=>s.name==='Quiet Rite'); const cost=sk.cost, before=totals('Kael').mp; baseJobs.Kael.stats.mag+=20; const after=totals('Kael').mp; baseJobs.Kael.stats.mag=old; return after-before===10 && sk.cost===cost;})()`);
check('AGI grants 0.10 percentage point CRIT per point', 'Math.abs(agilityCritBonusFromAgi(137)-.137)<.000001 && Math.abs(agilityCritBonusFromAgi(90)-.09)<.000001');
check('ECHO increases Ultimate potency', `(() => {const old=baseJobs.Sparky.stats.echo; const sk=baseJobs.Sparky.skills.find(s=>s.anim==='ultimate'); const before=ultimatePotencyMultiplier('Sparky',sk); baseJobs.Sparky.stats.echo+=20; const after=ultimatePotencyMultiplier('Sparky',sk); baseJobs.Sparky.stats.echo=old; return after>before;})()`);
check('Ultimate ranks improve at levels 12, 24 and 36', `(() => {const p=progressFor('Verseborn'), old=p.level; const ranks=[1,12,24,36].map(level=>(p.level=level,ultimateRank('Verseborn'))); p.level=old; return ranks.join(',')==='1,2,3,4';})()`);
check('All normal weapons and Echo bases have a Basic Attack effect', 'Object.values(gearDb).flat().filter(g=>g.slot==="weapon").every(g=>Boolean(weaponBasicAttackEffect(g)))');
check('Normal Attack restores exactly 6 percent Max MP and triggers weapon setup', `(() => {const p=progressFor('Mira'); p.talents=[]; const u=battleUnit('Mira'); u.mp=0; const foe=prepareEnemyForBattle(enemy('Basic Test',9999,1,'None','#555',1)); battle={party:[u],enemies:[foe],round:1,turnIndex:0,turnQueue:[{side:'party',id:'Mira'}],usedOnce:{},extraTurns:0,resolving:false}; mode='battle'; useSkill(u,battleSkills('Mira',u)[0],foe); __impact(); return u.mp===Math.round(u.maxmp*.06) && Boolean(statusOf(foe,'marked'));})()`);
check('Weapon Basic Attack effects never trigger from skills', `(() => {const u=battleUnit('Mira'); u.mp=999; const foe=prepareEnemyForBattle(enemy('Skill Test',9999,1,'None','#555',1)); battle={party:[u],enemies:[foe],round:1,turnIndex:0,turnQueue:[{side:'party',id:'Mira'}],usedOnce:{},extraTurns:0,resolving:false}; mode='battle'; useSkill(u,baseJobs.Mira.skills[2],foe); __impact(); return !statusOf(foe,'marked');})()`);
check('Flat MP-on-hit recovery scales but keeps its minimum', 'scaledMpOnHitRecovery({maxmp:20},2)===2 && scaledMpOnHitRecovery({maxmp:200},2)===8');
check('Mech and Shadowpriest scale from current stats and ECHO', `(() => {const g={id:'Glimmer',form:'mech'}, k={id:'Kael',form:'shadowpriest'}; return transformedStatMultiplier(g,'mag')>1 && transformedStatMultiplier(k,'mag')>1;})()`);
check('Capstone selection replaces only the previous capstone', `(() => {mode='walk'; const p=progressFor('Verseborn'); p.level=40; p.talents=talentTrees.Verseborn.filter(t=>t.tier<5).slice(0,8).map(t=>t.name); toggleTalent('Verseborn:Maestro of Flame'); toggleTalent('Verseborn:Voice of Ruin'); return p.talents.length===9 && !p.talents.includes('Maestro of Flame') && p.talents.includes('Voice of Ruin');})()`);
check('Talent reset is available only outside combat', `(() => {const p=progressFor('Verseborn'); mode='battle'; resetTalents('Verseborn'); const kept=p.talents.length; mode='walk'; resetTalents('Verseborn'); return kept>0 && p.talents.length===0;})()`);
check('Talent menu renders five tiers and fixed MP language', `(() => {state.party=Object.keys(baseJobs); selectedSkillHero='Mira'; menuTab='skills'; renderMenu(); return (el.menuBody.innerHTML.match(/class="talent-tier /g)||[]).length===5 && el.menuBody.innerHTML.includes('fixed MP') && !el.menuBody.innerHTML.includes('undefined');})()`);
check('Status sheet explains ECHO, AGI CRIT and fixed MP endurance', `(() => {const html=statusCardHtml('Sparky'); return html.includes('ECHO') && html.includes('AGI + CRIT') && statusStatHelp.some(row=>row[1].includes('fixed'));})()`);
check('Status menu shows one selected biography behind a top roster', `(() => {state.party=Object.keys(baseJobs); selectedStatusHero='Mira'; menuTab='status'; renderMenu(); const html=el.menuBody.innerHTML; return html.includes('class="status-roster"') && html.includes(characterBios.Mira) && (html.match(/class="menu-card status-card"/g)||[]).length===1 && (html.match(/data-status-hero=/g)||[]).length===state.party.length;})()`);
check('Every selectable character has a biography', `Object.keys(baseJobs).every(id=>characterBios[id]&&characterBios[id].length>80)`);
check('Three-enemy formation has one forward center and two lower rear units', `(() => {const top=enemyBattlePosition(0,3), middle=enemyBattlePosition(1,3), bottom=enemyBattlePosition(2,3); return middle[0]<top[0]&&top[0]===bottom[0]&&top[1]>=85&&middle[1]>top[1]&&bottom[1]>middle[1];})()`);
check('Speed buffs reorder actions without creating extra turns', `(() => {const a=battleUnit('Verseborn'), b=battleUnit('Glimmer'); const foe=prepareEnemyForBattle(enemy('Speed Test',100,1,'Fire','#555',1)); foe.stats.agi=Math.round(totals('Glimmer').agi*1.1); battle={party:[a,b],enemies:[foe],round:2,turnIndex:0,extraTurns:0,turnQueue:[{side:'party',id:a.id},{side:'enemy',index:0},{side:'party',id:b.id}]}; applySkillBuffs(a,[b],{buffs:[{type:'agilityUp'}]}); return battle.turnQueue.length===3 && battle.turnQueue[1].id===b.id && battle.extraTurns===0;})()`);
check('Weakness discovery remains intact', `(() => {state.activeParty=['Glimmer']; progressFor('Glimmer').talents=[]; const e={name:'Discovery Test',weak:'Earth'}; return !knownWeakness(e) && rememberWeakness(e) && knownWeakness(e);})()`);
check('Every Tier 2 offers exactly one damage or healing area conversion', `(() => {const expected={Verseborn:['Resonant Field','Resonant Verse','allEnemies'],Mira:['Voidthorn Rain','Voidthorn Mark','allEnemies'],Seerin:['Cinder Sanctuary','Cinder Guard','partyWide'],Torren:['Foundation Quake','Foundation Break','allEnemies'],Glimmer:['Patch Network','Patch Job','partyWide'],Kael:['Communal Rite','Quiet Rite','partyWide'],Sparky:['Memory Wildfire','Memory Flare','allEnemies']}; return Object.entries(expected).every(([id,[talentName,skillName,flag]])=>{const tierTwo=talentTrees[id].filter(t=>t.tier===2&&['aoeSkill','partyHeal'].includes(t.type)); progressFor(id).talents=[talentName]; const sk=battleSkills(id,{id}).find(s=>s.name===skillName); return tierTwo.length===1&&sk?.[flag]&&sk.desc.includes('every living');});})()`);
check('Area heals carry their distinct party buffs', `(() => {const expected={Seerin:['Cinder Sanctuary','Cinder Guard','holyFollowUp',.1,1],Glimmer:['Patch Network','Patch Job','combatDrone',.4,2],Kael:['Communal Rite','Quiet Rite','defenseUp',.12,2]}; return Object.entries(expected).every(([id,[talentName,skillName,type,value,duration]])=>{progressFor(id).talents=[talentName]; const sk=battleSkills(id,{id}).find(s=>s.name===skillName); const buff=sk?.buffs?.find(entry=>entry.type===type); return sk?.partyWide&&buff?.value===value&&buff?.duration===duration;});})()`);
check('Seerin clears all enemy Resonance without blocking new gains', `(() => {const foe=prepareEnemyForBattle(enemy('Resonance Test',999,1,'None','#555',1));foe.resonance=82;const sk=baseJobs.Seerin.skills.find(entry=>entry.name==='Oathbreak');const note=applyEnemyResonanceControl({id:'Seerin'},foe,sk);const gained=gainEnemyResonance(foe,40);return sk.cost===8&&foe.resonance===40&&gained===40&&!statusOf(foe,'resonanceLocked')&&note.includes('82 Resonance');})()`);
check('Kael removes half of enemy Resonance and locks gains for one action', `(() => {const foe=prepareEnemyForBattle(enemy('Resonance Test',999,1,'None','#555',1));foe.resonance=70;const sk=baseJobs.Kael.skills.find(entry=>entry.name==='Quiet Tithe');const note=applyEnemyResonanceControl({id:'Kael'},foe,sk);const blocked=gainEnemyResonance(foe,40);return sk.cost===9&&foe.resonance===35&&blocked===0&&statusOf(foe,'resonanceLocked')?.remaining===1&&note.includes('removes 35 Resonance');})()`);
check('Seerin Holy Follow-up adds ten percent once then expires', `(() => {const random=Math.random; Math.random=()=>.999; try {progressFor('Verseborn').talents=[]; const u=battleUnit('Verseborn'); u.mp=999; applyStatus(u,'holyFollowUp',{id:'Seerin'},{force:true,duration:1,value:.1}); const foe=prepareEnemyForBattle(enemy('Holy Follow-up Test',9999,1,'None','#555',1)); foe.hp=foe.max=9999; battle={party:[u],enemies:[foe],round:1,turnIndex:0,turnQueue:[{side:'party',id:u.id}],usedOnce:{},extraTurns:0,resolving:false}; mode='battle'; const sk=baseJobs.Verseborn.skills.find(s=>s.name==='Resonant Verse'); const base=Math.max(1,Math.round((sk.power+totals('Verseborn').mag+5)*outgoingDamageMultiplier(u,'magic',foe))); useSkill(u,sk,foe); __impact(); return 9999-foe.hp===base+Math.max(1,Math.round(base*.1))&&!statusOf(u,'holyFollowUp');} finally {Math.random=random;}})()`);
check('Shared Combat Drone uses Glimmer as its damage and talent source', `(() => {progressFor('Glimmer').talents=['Dual Drone Protocol']; progressFor('Torren').talents=[]; const u=battleUnit('Torren'); applyStatus(u,'combatDrone',{id:'Glimmer'},{force:true,duration:2,value:.4}); const drone=statusOf(u,'combatDrone'); const glimmerPower=(drone.value*(1+typedTalentValue('Glimmer','dronePower'))); const fromGlimmer=Math.round(totals('Glimmer').mag*glimmerPower); const fromTorren=Math.round(totals('Torren').mag*glimmerPower); return drone.source.id==='Glimmer'&&fromGlimmer>fromTorren;})()`);
check('Shared Combat Drone visibly fires after an ally damaging action', `(() => {const random=Math.random; Math.random=()=>.999; try {progressFor('Glimmer').talents=[]; progressFor('Torren').talents=[]; const u=battleUnit('Torren'); u.mp=999; applyStatus(u,'combatDrone',{id:'Glimmer'},{force:true,duration:2,value:.4}); const foe=prepareEnemyForBattle(enemy('Drone Test',9999,1,'None','#555',1)); foe.hp=foe.max=9999; battle={party:[u],enemies:[foe],round:1,turnIndex:0,turnQueue:[{side:'party',id:u.id}],usedOnce:{},extraTurns:0,resolving:false}; battleFloaters=[]; mode='battle'; useSkill(u,battleSkills('Torren',u)[0],foe); __impact(); const droneFloater=battleFloaters.find(entry=>entry.damageType==='Drone Tech'); return Boolean(droneFloater)&&droneFloater.amount>Math.round(totals('Glimmer').mag*.4)&&foe.hp<foe.max;} finally {Math.random=random;}})()`);
check('The four revised idle animations stay on clean neutral poses with slow breathing', `(() => {const cleanFrames={Verseborn:0,Mira:1,Glimmer:0,Seerin:0}; return Object.entries(cleanFrames).every(([id,frame])=>calmBattleIdleHeroes.has(id)&&battleFrameSequences[id].idle.every(value=>value===frame))&&battleIdleSourceCrops.Glimmer.x===380&&battleIdleSourceCrops.Seerin.x===248&&['Kael','Torren','Sparky'].every(id=>!calmBattleIdleHeroes.has(id));})()`);
check('Concurrent damage sources receive separate readable floater lanes', `(() => {const foe=prepareEnemyForBattle(enemy('Floater Test',9999,1,'None','#555',1)); battle={party:[],enemies:[foe]}; battleFloaters=[]; addBattleFloater(foe,100,{damageType:'Shadow'}); addBattleFloater(foe,20,{damageType:'Holy Fire',delayTicks:4}); addBattleFloater(foe,30,{damageType:'Drone Tech'}); return new Set(battleFloaters.map(entry=>entry.lane)).size===3&&battleFloaters.every(entry=>entry.target===foe)&&battleFloaterLaneOffsets.length>=3;})()`);
check('Damage and healing floaters remain for an extra half-second', 'BATTLE_FLOATER_LIFETIME===78');
check('Loot summaries show only compact colored gear names and types', `(() => {const drop={kind:'gear',name:'Echo Test Blade',rarity:'Epic',type:'Weapon',amount:1,stored:true}; const summary=lootSummaryContent(0,[drop]); return lootDropText(drop)==='Echo Test Blade [Weapon]'&&summary.html.includes('rarity-epic')&&summary.html.includes('<small>Weapon</small>')&&!summary.html.includes('affix');})()`);
check('Inventory separates consumables, quest items and sellable treasure', `inventoryCategory("Marla's Soup")==='consumables'&&inventoryCategory('Iron Chain Link')==='quest'&&inventoryCategory('Ash Ink')==='treasure'&&inventorySellPrice('Iron Chain Link')===0&&inventorySellPrice('Ash Ink')>0&&inventorySellPrice("Foreman's Black Ledger")>0`);
check('Gear and Items menus use selectable lists with one detail panel', `(() => {mode='menu'; state.party=Object.keys(baseJobs); selectedGearHero='Verseborn'; selectedGearSlot='weapon'; selectedGearRef=null; menuTab='gear'; renderMenu(); const gearHtml=el.menuBody.innerHTML; selectedItemCategory='gear'; selectedItemRef=null; menuTab='items'; renderMenu(); const itemHtml=el.menuBody.innerHTML; return gearHtml.includes('gear-selection-workspace')&&gearHtml.includes('selection-detail')&&itemHtml.includes('item-selection-workspace')&&itemHtml.includes('Consumables')&&itemHtml.includes('Treasure')&&itemHtml.includes('Quest Items');})()`);
check('Every equipment slot uses all five new visual archetypes', `(() => {const expected={weapon:[['Guildsteel Saber',0],['Shelter Staff',1],['Stonewake Maul',2],['Twin Voidthorns',3],['Voice of Verse',4]],armour:[['Ashcloak',0],['Sealbreak Vestment',1],['Workshop Coat',2],['Stonewake Mantle',3],['Flameguard Plate',4]],ring:[['Promise Ring',0],['Red Ember Band',1],['Faultline Signet',2],["Rava's Guard Ring",3],['Quiet Circuit',4]],necklace:[['Cinder Star',0],['Wyrmheart Ember',1],['Silent Reliquary',2],['Hearthwall Crest',3],['Gearheart Charm',4]],helmet:[['Songweaver Hood',0],['Firstlight Crown',1],['Stone Echo Helm',2],['Fleetglass Circlet',3],['Mira Top Hat',4]]}; return Object.entries(expected).every(([slot,entries])=>entries.every(([name,index])=>{const gear=gearByName(name);return gear?.slot===slot&&gearIconSheet(gear,'Verseborn')==='gear-'+slot+'-catalog'&&gearIconIndex(gear)===index;}));})()`);
check('Echo-Forged equipment inherits its base item art', `echoForgeGear.every(gear=>gearIconIndex(gear)===gearIconIndex(gearByName(gear.echoBase)))`);
check('Title menu has exactly the three requested exclusive states', `titleMenuEntries.map(entry=>entry.toUpperCase()).join('|')==='STORY MODE|EMBER HALL'&&titleSubmenuEntries[0].map(entry=>entry.toUpperCase()).join('|')==='NEW|CONTINUE|BACK'&&titleSubmenuEntries[1].map(entry=>entry.toUpperCase()).join('|')==='NEW RUN|CONTINUE RUN|BACK'`);
check('Title background stays fixed on the first supplied frame', `TITLE_BACKGROUND_FRAME===1&&loadTitleIdleFrames.toString().includes('[TITLE_BACKGROUND_FRAME]')&&!drawTitle.toString().includes('titleIdleFrameIndex')&&!drawTitle.toString().includes('drawTitleTwinkles')`);
check('Fixed title background keeps the existing menu selector as a separate overlay', `titleIdleFrames.length===0&&titleMenuEntries.join('|')==='Story Mode|Ember Hall'&&typeof drawTitleMenu==='function'&&drawTitle.toString().indexOf('drawTitleMenu(layout)')>drawTitle.toString().indexOf('fixedBackground')`);
check('Confirm replaces the main menu with one submenu and Back restores it', `(() => {const oldReady=runtimeAssetsReady,oldState=titleMenuState,oldMode=titleMenuIndex,oldAction=titleSubmenuIndex;try {runtimeAssetsReady=true;titleMenuState='main';titleMenuIndex=1;titleSubmenuIndex=0;activateTitleSelection();const opened=titleMenuState==='hall'&&titleSubmenuIndex===0;moveTitleSelection(2);activateTitleSelection();return opened&&titleMenuState==='main'&&titleMenuIndex===1&&titleSubmenuIndex===0;} finally {runtimeAssetsReady=oldReady;titleMenuState=oldState;titleMenuIndex=oldMode;titleSubmenuIndex=oldAction;}})()`);
check('Title pointer targets only the currently visible menu and separate footer prompt', `(() => {const oldImage=titleImage,oldState=titleMenuState;try {titleImage={naturalWidth:1448,naturalHeight:1086};const layout=titleImageLayout(),event=(x,y)=>({clientX:layout.x+x*layout.scale,clientY:layout.y+y*layout.scale});titleMenuState='main';const main=titleMenuPointerTarget(event(724,480))?.index===0&&titleMenuPointerTarget(event(724,529))?.index===1;titleMenuState='story';const sub=titleMenuPointerTarget(event(724,465))?.kind==='action'&&titleMenuPointerTarget(event(724,514))?.index===1&&titleMenuPointerTarget(event(724,563))?.index===2;return main&&sub&&titleMenuPointerTarget(event(724,674))?.kind==='confirm';} finally {titleImage=oldImage;titleMenuState=oldState;}})()`);
check('Title Continue routes Story and Ember Hall to their existing separate saves', `(() => {const oldReady=runtimeAssetsReady,oldState=titleMenuState,oldMode=titleMenuIndex,oldAction=titleSubmenuIndex,oldStory=startTitleGame,oldHall=startHallBattles,oldStorySave=localStorage.getItem(SAVE_KEY),oldHallSave=localStorage.getItem(HALL_SAVE_KEY);try {runtimeAssetsReady=true;localStorage.setItem(SAVE_KEY,'{}');localStorage.setItem(HALL_SAVE_KEY,'{}');let routes=[];startTitleGame=continued=>routes.push('story:'+continued);startHallBattles=continued=>routes.push('hall:'+continued);titleMenuState='story';titleMenuIndex=0;titleSubmenuIndex=1;activateTitleSelection();titleMenuState='hall';titleMenuIndex=1;titleSubmenuIndex=1;activateTitleSelection();return routes.join('|')==='story:true|hall:true';} finally {runtimeAssetsReady=oldReady;titleMenuState=oldState;titleMenuIndex=oldMode;titleSubmenuIndex=oldAction;startTitleGame=oldStory;startHallBattles=oldHall;oldStorySave===null?localStorage.removeItem(SAVE_KEY):localStorage.setItem(SAVE_KEY,oldStorySave);oldHallSave===null?localStorage.removeItem(HALL_SAVE_KEY):localStorage.setItem(HALL_SAVE_KEY,oldHallSave);}})()`);
check('Recruit scenes and Ember Hall bosses select their dedicated music only', `(() => {const oldMode=mode,oldScene=activeRecruitScene,oldBattle=battle;try {mode='talk';activeRecruitScene={id:'music-test'};const sceneTrack=trackForScene();activeRecruitScene=null;const ordinaryTalk=trackForScene();mode='battle';battle={hallBoss:true};const hallBossTrack=trackForScene();battle={hallBoss:false};const ordinaryBattle=trackForScene();return music.cutscene.src.endsWith('cutscenes.mp3')&&music.hallBoss.src.endsWith('ember-hall-boss-battle.mp3')&&sceneTrack==='cutscene'&&ordinaryTalk!=='cutscene'&&hallBossTrack==='hallBoss'&&ordinaryBattle==='battle';} finally {mode=oldMode;activeRecruitScene=oldScene;battle=oldBattle;}})()`);
check('Normal battles alternate two songs while Hall bosses do not consume a turn', `(() => {const oldIndex=normalBattleTrackIndex;try {normalBattleTrackIndex=0;const sequence=[battleMusicForEncounter(false),battleMusicForEncounter(false),battleMusicForEncounter(true),battleMusicForEncounter(false),battleMusicForEncounter(false)];return music.battleAlt.src.endsWith('battle-jrpg-2.mp3')&&sequence.join('|')==='battle|battleAlt|hallBoss|battle|battleAlt'&&normalBattleTrackIndex===4;} finally {normalBattleTrackIndex=oldIndex;}})()`);
check('Hall Battles has a separate persistent save', `(() => {state.gameMode='hallBattles'; const hall=activeSaveKey(); state.gameMode='story'; return hall===HALL_SAVE_KEY&&activeSaveKey()===SAVE_KEY&&HALL_SAVE_KEY!==SAVE_KEY;})()`);
check('A new Hall run resets Hall progress and Scene Memories only', `(() => {const oldStory=localStorage.getItem(SAVE_KEY), oldHall=localStorage.getItem(HALL_SAVE_KEY), oldScenes=localStorage.getItem(HALL_SCENE_HISTORY_KEY); try {localStorage.setItem(SAVE_KEY,'story-save');localStorage.setItem(HALL_SAVE_KEY,'hall-save');localStorage.setItem(HALL_SCENE_HISTORY_KEY,'scene-history');state.party=['Verseborn','Mira'];state.gold=9999;state.hallBattles={unlockedStage:40,clearedStages:[1,2,3],recruitStages:[3],pendingRecruit:6};resetHallBattleRun();return localStorage.getItem(SAVE_KEY)==='story-save'&&!localStorage.getItem(HALL_SAVE_KEY)&&!localStorage.getItem(HALL_SCENE_HISTORY_KEY)&&state.party.join(',')==='Verseborn'&&state.gold===180&&state.hallBattles.unlockedStage===1&&state.hallBattles.clearedStages.length===0;} finally {[[SAVE_KEY,oldStory],[HALL_SAVE_KEY,oldHall],[HALL_SCENE_HISTORY_KEY,oldScenes]].forEach(([key,value])=>value===null?localStorage.removeItem(key):localStorage.setItem(key,value));}})()`);
check('Continue Hall restores progress without clearing Scene Memories', `(() => {const oldHall=localStorage.getItem(HALL_SAVE_KEY), oldScenes=localStorage.getItem(HALL_SCENE_HISTORY_KEY), oldAssets=runtimeAssetsReady; try {mode='walk';state.gameMode='hallBattles';state.map='emberHallBattles';state.party=['Verseborn','Mira'];state.activeParty=['Verseborn','Mira'];state.hallBattles={unlockedStage:12,clearedStages:[1,2,3],recruitStages:[3],pendingRecruit:0};localStorage.setItem(HALL_SCENE_HISTORY_KEY,'scene-history');saveGame(HALL_SAVE_KEY);state.party=['Verseborn'];state.hallBattles={unlockedStage:1,clearedStages:[],recruitStages:[],pendingRecruit:0};runtimeAssetsReady=true;startHallBattles(true);return state.party.includes('Mira')&&state.hallBattles.unlockedStage===12&&localStorage.getItem(HALL_SCENE_HISTORY_KEY)==='scene-history';} finally {runtimeAssetsReady=oldAssets;[[HALL_SAVE_KEY,oldHall],[HALL_SCENE_HISTORY_KEY,oldScenes]].forEach(([key,value])=>value===null?localStorage.removeItem(key):localStorage.setItem(key,value));}})()`);
check('Hall hub uses its own art with Marla, Glimmer and the Trial Gate', `(() => {const hub=maps.emberHallBattles; return hub.background==='ember-hall-battle'&&hub.collision==='lantern'&&hub.exits.length===0&&['Marla','Glimmer','Stage'].every(id=>hub.points.some(point=>point.id===id));})()`);
check('Hall Trial Gate uses the dedicated four-frame selector machine', `STAGE_SELECTOR_ASSET==='assets/ui/stage-selector-sheet.webp'&&STAGE_SELECTOR_FRAMES===4`);
check('Hall battle map contains forty ordered replayable records', `HALL_BATTLE_BLUEPRINTS.length===40&&HALL_BATTLE_BLUEPRINTS.every((entry,index)=>entry.stage===index+1&&maps[entry.mapId]&&entry.enemies.length>=1)`);
check('Hall enemies use the selected stage level and normal XP formula', `(() => {const units=hallEnemiesForStage(40).map(unit=>prepareEnemyForBattle(unit)); return units.length===3&&units.every(unit=>unit.level===40&&unit.xp===14+40*7);})()`);
check('Cleared Hall stages render as replayable while future stages stay locked', `(() => {state.gameMode='hallBattles'; state.hallBattles={unlockedStage:2,clearedStages:[1],recruitStages:[],pendingRecruit:0}; renderHallBattleMap(); const html=el.menuBody.innerHTML; return (html.match(/data-hall-stage=/g)||[]).length===40&&html.includes('STAGE 01')&&html.includes('CLEARED / REPLAY')&&html.includes('STAGE 03')&&html.includes('is-locked');})()`);
check('Only a first Hall clear unlocks progress and schedules recruitment', `(() => {state.party=['Verseborn']; state.echoForgeRank=0; state.hallBattles={unlockedStage:3,clearedStages:[1,2],recruitStages:[],pendingRecruit:0}; const first=recordHallBattleClear(3), replay=recordHallBattleClear(3); return first&&!replay&&state.hallBattles.unlockedStage===4&&state.hallBattles.pendingRecruit===3&&state.echoForgeRank===3&&state.hallBattles.clearedStages.join(',')==='1,2,3';})()`);
check('Hall recruitment offers every existing companion at three-stage intervals', `HALL_RECRUIT_INTERVAL===3&&HALL_RECRUITS.length===6&&HALL_RECRUITS.every(id=>baseJobs[id]&&id!=='Verseborn')`);
check('Glimmer sells two repeatable Echo Hunt items per rank through forty', `(() => {state.echoForgeRank=40; state.endgameRank=0; const wares=vendorWares('workshop').filter(ware=>ware.kind==='gear'&&echoForgeGearNames.has(ware.name)); return echoForgeGear.length===80&&wares.length===80&&new Set(wares.map(ware=>ware.name)).size===80&&Array.from({length:40},(_,index)=>wares.filter(ware=>gearByName(ware.name).echoRank===index+1).length===2).every(Boolean);})()`);
check('Hall stages 1-20 grant new random equipment from Uncommon through Legendary', `(() => {const oldRandom=Math.random, oldOwned=[...state.ownedGear], oldCopies={...state.gearCopies}, oldRarities={...state.gearRarities}, oldAffixes=structuredClone(state.gearAffixes), oldInstances=structuredClone(state.gearInstances), oldNext=state.nextGearInstance; try {const rolled=[0,.26,.51,.76].map(value=>(Math.random=()=>value,rollHallGearRarity())); Math.random=()=>0; const rewards={drops:[],gearDrops:[]}; const awarded=guaranteeHallBattleGearReward(rewards,20); return rolled.join(',')==='Uncommon,Rare,Epic,Legendary'&&rewards.gearDrops.length===1&&rewards.drops.length===1&&rewards.drops[0].kind==='gear'&&HALL_STANDARD_GEAR_POOL.some(gear=>gear.name===awarded.name)&&HALL_GEAR_RARITIES.includes(awarded.rarity);} finally {Math.random=oldRandom; state.ownedGear=oldOwned; state.gearCopies=oldCopies; state.gearRarities=oldRarities; state.gearAffixes=oldAffixes; state.gearInstances=oldInstances; state.nextGearInstance=oldNext; gearInstances=state.gearInstances;}})()`);
check('Hall stages 21-40 always grant a new Legendary with four affixes', `(() => {const oldRandom=Math.random, oldOwned=[...state.ownedGear], oldCopies={...state.gearCopies}, oldRarities={...state.gearRarities}, oldAffixes=structuredClone(state.gearAffixes), oldInstances=structuredClone(state.gearInstances), oldNext=state.nextGearInstance; let roll=0; try {state.ownedGear=state.ownedGear.filter(name=>!HALL_LEGENDARY_GEAR_POOL.some(gear=>gear.name===name)); HALL_LEGENDARY_GEAR_POOL.forEach(gear=>state.gearCopies[gear.name]=0); Math.random=()=>((roll++*.173)%1); const rewards={drops:[],gearDrops:[]}; const awarded=guaranteeHallBattleGearReward(rewards,21); return awarded.rarity==='Legendary'&&HALL_LEGENDARY_GEAR_POOL.some(gear=>gear.name===awarded.name)&&gearAffixes(awarded.ref).length===4&&rewards.gearDrops.length===1;} finally {Math.random=oldRandom; state.ownedGear=oldOwned; state.gearCopies=oldCopies; state.gearRarities=oldRarities; state.gearAffixes=oldAffixes; state.gearInstances=oldInstances; state.nextGearInstance=oldNext; gearInstances=state.gearInstances;}})()`);
check('Seven deep Hall milestones distribute one unique ultimate weapon per hero', `HALL_ULTIMATE_REWARD_STAGES.size===7&&HALL_ULTIMATE_WEAPONS.length===7&&new Set(HALL_ULTIMATE_WEAPONS.flatMap(gear=>gearOwners[gear.name]||[])).size===7&&HALL_ULTIMATE_WEAPONS.every(gear=>weaponBasicAttackEffect(gear)&&gearEffects(gear).length)`);
check('Deep Hall ultimate milestones prioritize missing hero weapons on clears and replays', `(() => {const oldOwned=[...state.ownedGear], oldCopies={...state.gearCopies}; try {HALL_ULTIMATE_WEAPONS.forEach(gear=>{state.ownedGear=state.ownedGear.filter(name=>name!==gear.name);state.gearCopies[gear.name]=0;}); const candidates=hallGearRewardCandidates(21); return candidates.length===7&&candidates.every(gear=>HALL_ULTIMATE_WEAPONS.includes(gear));} finally {state.ownedGear=oldOwned;state.gearCopies=oldCopies;}})()`);
check('All party XP sources award exactly twice their listed amount', `(() => {const oldParty=[...state.party], oldActive=[...state.activeParty], oldProgress=structuredClone(state.heroProgress); try {state.party=['Verseborn','Mira'];state.activeParty=['Verseborn'];state.heroProgress.Verseborn={level:1,xp:0,talents:[],pendingMilestones:[]};state.heroProgress.Mira={level:1,xp:0,talents:[],pendingMilestones:[]};const summary=awardPartyXp(20,'test');return XP_MULTIPLIER===2&&state.heroProgress.Verseborn.xp===40&&state.heroProgress.Mira.xp===26&&summary.startsWith('40 XP');} finally {state.party=oldParty;state.activeParty=oldActive;state.heroProgress=oldProgress;}})()`);
check('Glimmer and Kael transformation Ultimates unlock at level ten', `(() => {const forms={Glimmer:'mech',Kael:'shadowpriest'}, oldLevels=Object.fromEntries(Object.keys(forms).map(id=>[id,progressFor(id).level])); try {return TRANSFORMATION_UNLOCK_LEVEL===10&&Object.entries(forms).every(([id,form])=>{progressFor(id).level=9;const locked=!battleSkills(id,{id}).some(skillEntry=>skillEntry.transform===form);progressFor(id).level=10;const unlocked=battleSkills(id,{id}).filter(skillEntry=>skillEntry.transform===form);return locked&&unlocked.length===1&&unlocked[0].anim==='ultimate';});} finally {Object.entries(oldLevels).forEach(([id,level])=>progressFor(id).level=level);}})()`);
check('Repeated Hall equipment drops remain separate copies with independent rarity and affixes', `(() => {const name='Ashrunner Knife', oldOwned=[...state.ownedGear], oldCopies={...state.gearCopies}, oldRarities={...state.gearRarities}, oldAffixes=structuredClone(state.gearAffixes), oldInstances=structuredClone(state.gearInstances), oldNext=state.nextGearInstance; try {state.ownedGear=state.ownedGear.filter(entry=>entry!==name); state.gearCopies[name]=0; delete state.gearRarities[name]; delete state.gearAffixes[name]; Object.keys(gearInstances).filter(ref=>gearInstance(ref)?.name===name).forEach(ref=>delete gearInstances[ref]); const a=addOwnedGear(name,1,{rarity:'Uncommon',rollAffixes:true,separateCopy:true})[0], b=addOwnedGear(name,1,{rarity:'Legendary',rollAffixes:true,separateCopy:true})[0]; return a!==b&&gearRarity(a)==='Uncommon'&&gearRarity(b)==='Legendary'&&gearAffixes(a).length===1&&gearAffixes(b).length===4&&ownedGearRefs('weapon','Verseborn').includes(a)&&ownedGearRefs('weapon','Verseborn').includes(b);} finally {state.ownedGear=oldOwned; state.gearCopies=oldCopies; state.gearRarities=oldRarities; state.gearAffixes=oldAffixes; state.gearInstances=oldInstances; state.nextGearInstance=oldNext; gearInstances=state.gearInstances;}})()`);
check('Hall battle endings fully restore HP and MP before returning to the Hall', `(() => {state.party=['Verseborn','Mira']; baseJobs.Verseborn.hp=1; baseJobs.Verseborn.mp=0; baseJobs.Mira.hp=2; baseJobs.Mira.mp=1; returnToHallAfterBattle(); return state.map==='emberHallBattles'&&state.party.every(id=>baseJobs[id].hp===totals(id).max&&baseJobs[id].mp===totals(id).mp);})()`);
check('Ten new battle arenas are registered and available as compact WebP assets', `(() => {const ids=['cinder-terrace','lantern-tavern','reverie-garden','reverie-library','guildspire-marble','cinder-sunset','fallen-dawn','cinder-ruins','cinder-cataclysm','lantern-stage']; return ids.every(id=>battleImageFiles[id]?.endsWith('.webp'));})()`);
check('Battle arenas follow locations and give special Hall encounters their own stage', `(() => {const oldMap=state.map, oldBattle=battle; try {battle=null; const expected={lantern:'lantern-stage',ashLane:'cinder-terrace',ashDock:'cinder-sunset',reverieCourt:'reverie-garden',reverieArchive:'reverie-library',guildHall:'guildspire-marble',emberArmory:'cinder-ruins',dawnCauseway:'fallen-dawn'}; const mapped=Object.entries(expected).every(([mapId,arena])=>(state.map=mapId,battleArenaFor(maps[mapId])===arena)); const hallArenas=new Set(HALL_BATTLE_BLUEPRINTS.map(info=>(battle={hallStage:info.stage},state.map=info.mapId,battleArenaFor(maps[info.mapId])))); battle={hallStage:40}; state.map='alarm'; return mapped&&hallArenas.size>=10&&battleArenaFor(maps.alarm)==='cinder-cataclysm';} finally {state.map=oldMap; battle=oldBattle;}})()`);
check('Every Hall recruit has one welcome, humorous and warm scene with compact dialogue', `(() => {const history={seen:[],lastByRecruit:{}}; return HALL_RECRUITS.every(recruit=>{const scenes=RECRUIT_SCENES.filter(scene=>scene.recruit===recruit); return scenes.length===3&&['welcome','humorous','warm'].every(variant=>scenes.filter(scene=>scene.variant===variant).length===1)&&scenes.every(scene=>{const partner=scene.preferred[0]||'Verseborn'; const actors=scene.cast||[partner,recruit]; const lines=scene.build({recruit,partner,history,actors}); return lines.length>=4&&lines.length<=7&&lines.filter(line=>line[2]).length<=4;});});})()`);
check('Recruit scene IDs stay unique and existing welcome references stay unchanged', `(() => {const ids=RECRUIT_SCENES.map(scene=>scene.id); const expected={Mira:['mira-welcome','Spare Blades','training-room'],Seerin:['seerin-welcome','Practice Blades','training-room'],Kael:['kael-welcome','A Quiet Shelf','kael-library'],Torren:['torren-welcome','Sit Down','torren-kitchen'],Sparky:['sparky-welcome','A Shiny Welcome','sparky-coop'],Glimmer:['glimmer-welcome','Bench Rights','glimmer-lab']}; return new Set(ids).size===ids.length&&Object.entries(expected).every(([recruit,[id,title,room]])=>{const scene=RECRUIT_SCENES.find(entry=>entry.recruit===recruit&&entry.variant==='welcome');return scene?.id===id&&scene.title===title&&scene.room===room;});})()`);
check('Recruit scenes use eight supplied room images plus the existing Trial Room map', `Object.keys(recruitSceneImageFiles).length===8&&Object.values(recruitSceneImageFiles).every(file=>file.endsWith('.webp'))&&Object.keys(RECRUIT_SCENE_ROOM_NAMES).every(id=>id==='trial-room'||recruitSceneImageFiles[id])&&RECRUIT_SCENES.find(scene=>scene.id===EMBER_HALL_INTRO_ID)?.room==='trial-room'&&maps.emberHallBattles.background==='ember-hall-battle'`);
check('Updated welcome scenes contain the requested full-roster dialogue', `(() => {const expected={'mira-welcome':['You carry too many knives.','And still not enough.','At last, a woman of refined priorities.','If you\\'re staying, you train properly.','Then try to keep up.'],'seerin-welcome':['You entered like a knight from a story.','I prefer prepared.','That still sounds dramatic.','Good. Then let\\'s test your footing.','Now this feels like home.'],'kael-welcome':['Before anything else, there are hall rules.','A thrilling opening.','Do unstable devices have a shelf?','No.','He truly is the spine of this place.'],'torren-welcome':['Good. Sit down.','An excellent first command.','Stew first. Questions later.','Prrrp!','No, you can\\'t have the whole pot.'],'sparky-welcome':['Behold: the smallest legend in the hall.','Prrr!','...That is unfairly cute.','He\\'s adorable.','Excellent. He has defeated you both.'],'glimmer-welcome':['Good news. I improved it.','Why is it smoking?','Because progress is happening.','I admire the confidence. I fear the result.','Both are correct.']}; const actors=['Verseborn',...HALL_RECRUITS]; const history={seen:[],lastByRecruit:{}}; return Object.entries(expected).every(([id,text])=>RECRUIT_SCENES.find(scene=>scene.id===id).build({partner:'Verseborn',history,actors}).map(line=>line[1]).join('|')===text.join('|'));})()`);
check('The first Hall arrival keeps its exact compact introduction and single effect', `(() => {const scene=RECRUIT_SCENES.find(entry=>entry.id===EMBER_HALL_INTRO_ID),lines=scene.build({});return scene.title==='Welcome to Ember Hall'&&lines.map(line=>line[1]).join('|')==="So. This is Ember Hall.|I expected more banners. Possibly a choir.|Give me twenty minutes.|You fight the trials. You come back here. You get stronger.|And ideally remain mostly alive.|That too.|When you're ready, step into the trial."&&lines.filter(line=>line[2]?.effect).length===1;})()`);
check('Welcome scenes give each staged character at most one primary action and one scene effect', `RECRUIT_SCENES.filter(scene=>scene.variant==='welcome').every(scene=>{const lines=scene.build({partner:'Verseborn',history:{seen:[],lastByRecruit:{}},actors:scene.cast||[]});const actors=lines.map(line=>line[2]?.actor).filter(Boolean);return new Set(actors).size===actors.length&&lines.filter(line=>line[2]?.effect).length<=1;})`);
check('Welcome actions use short scene-specific motions without spins or generic emotes', `(() => {const expected=['welcome-step','entrance','tool-tap','practice-strike','spar-dodge','flourish','dagger-flip','shelf-place','shelf-straighten','stir','small-step','hop-to-pot','fly-oval','approach-lean','reach','tinker-recoil','recoil'];const actions=RECRUIT_SCENES.filter(scene=>scene.variant==='welcome').flatMap(scene=>[scene.cast||[],['Verseborn',scene.recruit]].flatMap(actors=>scene.build({partner:'Verseborn',history:{seen:[],lastByRecruit:{}},actors}).flatMap(line=>line[2]?[line[2],...(line[2].with||[])]:[])));return expected.every(motion=>actions.some(action=>action.motion===motion))&&actions.every(action=>!['spin','circle','hop'].includes(action.motion)&&!action.emote&&action.duration>=60&&action.duration<=180);})()`);
check('Mira and Seerin share a controlled practice exchange', `(() => {const lines=RECRUIT_SCENES.find(scene=>scene.id==='mira-welcome').build({actors:['Verseborn','Seerin','Mira'],history:{seen:[],lastByRecruit:{}}});const spar=lines.map(line=>line[2]).find(action=>action?.motion==='practice-strike');return spar?.with?.length===1&&spar.with[0].actor==='Mira'&&spar.with[0].motion==='spar-dodge';})()`);
check('Scene motion profiles move, pose and settle back to idle', `(() => {const strike={facing:3,anim:'melee',motion:'practice-strike',actionDx:0},dodge={facing:1,anim:'melee',motion:'spar-dodge',actionDx:0},stir={facing:1,anim:'melee',motion:'stir',actionDx:0},recoil={facing:3,anim:'walk',motion:'recoil',actionDx:0};const strikeHit=recruitScenePoseAt(strike,.4),strikeDone=recruitScenePoseAt(strike,1),dodgeHit=recruitScenePoseAt(dodge,.5),stirA=recruitScenePoseAt(stir,.12),stirB=recruitScenePoseAt(stir,.2),recoilHit=recruitScenePoseAt(recoil,.5),done=recruitScenePoseAt(recoil,1,false);return strikeHit.x>0&&strikeHit.anim==='melee'&&Math.abs(strikeDone.x)<.01&&dodgeHit.x>0&&stirA.x!==stirB.x&&recoilHit.x<0&&done.x===0&&done.y===0&&done.anim==='idle';})()`);
check('Sparky follows an airborne oval and finishes hovering at his start point', `(() => {const sparky={facing:1,anim:'walk',motion:'fly-oval',actionDx:0};const start=recruitScenePoseAt(sparky,0),up=recruitScenePoseAt(sparky,.25),right=recruitScenePoseAt(sparky,.5),down=recruitScenePoseAt(sparky,.75),finish=recruitScenePoseAt(sparky,1);return up.y<start.y&&right.x>up.x&&down.y>right.y&&finish.x<down.x&&Math.abs(finish.x-start.x)<.01&&finish.y<0&&finish.anim==='walk';})()`);
check('First recruitment welcomes once, then rotates later variants without repeats', `(() => {const welcome=selectRecruitScene('Mira',{seen:[],lastByRecruit:{}}); const funny=selectRecruitScene('Mira',{seen:['mira-welcome'],lastByRecruit:{Mira:'mira-welcome'}}); const warm=selectRecruitScene('Mira',{seen:['mira-welcome','mira-humorous'],lastByRecruit:{Mira:'mira-humorous'}}); const rotated=selectRecruitScene('Mira',{seen:['mira-welcome','mira-humorous','mira-warm'],lastByRecruit:{Mira:'mira-warm'}}); return welcome.variant==='welcome'&&funny.variant==='humorous'&&warm.variant==='warm'&&rotated.variant==='humorous';})()`);
check('Scene partners and staged actors are limited to the current run roster', `(() => {state.party=['Verseborn','Mira']; const scene=RECRUIT_SCENES.find(entry=>entry.id==='mira-humorous'); const partner=recruitScenePartner(scene); const actors=recruitSceneActors(scene,partner); return partner==='Verseborn'&&actors.length===2&&actors.every(actor=>state.party.includes(actor.id))&&!actors.some(actor=>actor.id==='Glimmer');})()`);
check('Recruit scene playback uses portraits, short actions and a visible skip state', `(() => {localStorage.removeItem(HALL_SCENE_HISTORY_KEY); state.gameMode='hallBattles'; state.party=['Verseborn','Mira']; state.activeParty=['Verseborn','Mira']; const scene=RECRUIT_SCENES.find(entry=>entry.id==='mira-welcome'); const started=playRecruitScene(scene); const history=loadRecruitSceneHistory(); const valid=started&&mode==='talk'&&talkSkippable&&talkPortraits.join(',')==='Verseborn,Mira'&&history.seen.includes(scene.id)&&scene.build({partner:'Verseborn',history,actors:['Verseborn','Mira']}).some(line=>line[2]?.anim); skipTalk(); return valid&&mode==='walk'&&!activeRecruitScene&&!talkSkippable;})()`);
check('Skipping a recruitment scene does not change resources or Hall progress', `(() => {localStorage.removeItem(HALL_SCENE_HISTORY_KEY); state.gameMode='hallBattles'; state.party=['Verseborn','Kael']; state.activeParty=['Verseborn','Kael']; state.gold=321; state.resonance=17; state.hallBattles={unlockedStage:8,clearedStages:[1,2,3],recruitStages:[3],pendingRecruit:0}; const before=JSON.stringify({gold:state.gold,resonance:state.resonance,hall:state.hallBattles}); playRecruitScene(RECRUIT_SCENES.find(scene=>scene.id==='kael-welcome')); skipTalk(); return before===JSON.stringify({gold:state.gold,resonance:state.resonance,hall:state.hallBattles});})()`);
check('Scene Memories only lists seen scenes for recruits present in this run', `(() => {state.gameMode='hallBattles'; state.party=['Verseborn','Mira']; saveRecruitSceneHistory({seen:['mira-welcome','seerin-welcome'],lastByRecruit:{Mira:'mira-welcome',Seerin:'seerin-welcome'}}); const html=sceneMemoriesHtml(); return html.includes('data-replay-scene="mira-welcome"')&&!html.includes('data-replay-scene="seerin-welcome"')&&!html.includes('mira-humorous');})()`);
check('Existing Hall saves expose missed first-arrival scenes without autoplaying them', `(() => {localStorage.removeItem(HALL_SCENE_HISTORY_KEY); state.gameMode='hallBattles'; state.party=['Verseborn',...HALL_RECRUITS]; const html=sceneMemoriesHtml(); return html.includes('Unseen Arrivals')&&(html.match(/data-play-arrival-scene=/g)||[]).length===HALL_RECRUITS.length+1&&mode!=='talk';})()`);
check('Playing a missed arrival moves it into Scene Memories', `(() => {localStorage.removeItem(HALL_SCENE_HISTORY_KEY); state.gameMode='hallBattles'; state.party=['Verseborn','Mira']; state.activeParty=['Verseborn','Mira']; const started=playUnseenArrival('mira-welcome'); skipTalk(); const html=sceneMemoriesHtml(); return started&&html.includes('data-replay-scene="mira-welcome"')&&!html.includes('data-play-arrival-scene="mira-welcome"');})()`);
check('A fresh Hall starts its intro once while Continue Hall does not retrigger it', `(() => {const oldHall=localStorage.getItem(HALL_SAVE_KEY),oldScenes=localStorage.getItem(HALL_SCENE_HISTORY_KEY),oldAssets=runtimeAssetsReady; try {runtimeAssetsReady=true;localStorage.removeItem(HALL_SAVE_KEY);localStorage.removeItem(HALL_SCENE_HISTORY_KEY);startHallBattles(false);const fresh=mode==='talk'&&activeRecruitScene?.id===EMBER_HALL_INTRO_ID&&loadRecruitSceneHistory().seen.includes(EMBER_HALL_INTRO_ID);skipTalk();saveGame(HALL_SAVE_KEY);startHallBattles(true);return fresh&&mode==='walk'&&!activeRecruitScene&&loadRecruitSceneHistory().seen.includes(EMBER_HALL_INTRO_ID);} finally {runtimeAssetsReady=oldAssets;activeRecruitScene=null;mode='walk';[[HALL_SAVE_KEY,oldHall],[HALL_SCENE_HISTORY_KEY,oldScenes]].forEach(([key,value])=>value===null?localStorage.removeItem(key):localStorage.setItem(key,value));}})()`);
check('The Hall introduction has one memory entry and can replay without changing progress', `(() => {const oldScenes=localStorage.getItem(HALL_SCENE_HISTORY_KEY); try {state.gameMode='hallBattles';state.party=['Verseborn'];state.activeParty=['Verseborn'];state.gold=222;state.hallBattles={unlockedStage:7,clearedStages:[1,2],recruitStages:[],pendingRecruit:0};saveRecruitSceneHistory({seen:[EMBER_HALL_INTRO_ID],lastByRecruit:{Verseborn:EMBER_HALL_INTRO_ID}});const html=sceneMemoriesHtml(),before=JSON.stringify({gold:state.gold,hall:state.hallBattles}),started=replayRecruitScene(EMBER_HALL_INTRO_ID);skipTalk();return (html.match(/data-replay-scene="ember-hall-welcome"/g)||[]).length===1&&started&&before===JSON.stringify({gold:state.gold,hall:state.hallBattles});} finally {activeRecruitScene=null;mode='walk';oldScenes===null?localStorage.removeItem(HALL_SCENE_HISTORY_KEY):localStorage.setItem(HALL_SCENE_HISTORY_KEY,oldScenes);}})()`);
check('Welcome scene actors stay roster-aware except for the Hall introduction guides', `(() => {state.party=['Verseborn','Kael'];const kael=RECRUIT_SCENES.find(scene=>scene.id==='kael-welcome'),kaelActors=recruitSceneActors(kael,recruitScenePartner(kael)),kaelLines=kael.build({partner:'Verseborn',history:{seen:[],lastByRecruit:{}},actors:kaelActors.map(actor=>actor.id)}),intro=RECRUIT_SCENES.find(scene=>scene.id===EMBER_HALL_INTRO_ID),introActors=recruitSceneActors(intro,null);return kaelActors.map(actor=>actor.id).join(',')==='Verseborn,Kael'&&!kaelLines.some(line=>line[0]==='Glimmer')&&introActors.map(actor=>actor.id).join(',')==='Verseborn,Marla,Glimmer';})()`);
check('Recruit scene casts are staged in the middle of the screen', `(() => {state.party=['Verseborn',...HALL_RECRUITS];return RECRUIT_SCENES.every(scene=>recruitSceneActors(scene,recruitScenePartner(scene)).every(actor=>actor.baseline>=128&&actor.baseline<=140));})()`);
check('Recruit scene speakers and staged cast have existing dialogue portraits', `RECRUIT_SCENES.every(scene=>portraitSources[scene.recruit]&&scene.preferred.every(id=>portraitSources[id])&&(scene.cast||[]).every(id=>portraitSources[id]))`);
check('Mira and Verseborn gain two-turn single-target Silence skills', `(() => {const mira=baseJobs.Mira.skills.find(skillEntry=>skillEntry.name==='Cut the Tongue'),verseborn=baseJobs.Verseborn.skills.find(skillEntry=>skillEntry.name==='Hushed Refrain');return STATUS_DEFS.silence.duration===2&&mira?.anim==='melee'&&mira.power>=20&&mira.status?.type==='silence'&&mira.status.duration===2&&verseborn?.element==='Sound'&&verseborn.power>0&&verseborn.status?.type==='silence'&&verseborn.status.duration===2;})()`);
check('Cut the Tongue applies Silence and two-turn Shadow Exposed', `(() => {const source=battleUnit('Mira'),target={name:'Exposure Test',hp:100,max:100,statuses:[],weak:'Fire'},sk=baseJobs.Mira.skills.find(entry=>entry.name==='Cut the Tongue');battle={party:[source],enemies:[target],round:1,turnIndex:0,turnQueue:[{side:'party',id:'Mira'}],usedOnce:{},extraTurns:0,resolving:false};applySkillStatuses(source,target,sk);return statusOf(target,'silence')?.remaining===2&&statusOf(target,'shadowExposed')?.remaining===2&&skillHitsElementWeakness(target,sk);})()`);
check('Voidthorn Mark gets its larger Shadow Exposed payoff', `(() => {const sk=baseJobs.Mira.skills.find(entry=>entry.name==='Voidthorn Mark'),target={hp:100,max:100,statuses:[{type:'shadowExposed',remaining:2}],weak:'Fire'};return sk.shadowExposureBonus===.6&&Math.abs(skillWeaknessMultiplier('Mira',sk,target)-1.55*1.6*(1+effectValue('Mira','weaknessDamage')))<.000001;})()`);
check('Silent Step doubles Mira Stun chance for its own turn and the next', `(() => {const source=battleUnit('Mira'),sk=baseJobs.Mira.skills.find(entry=>entry.name==='Silent Step'),base=effectValue('Mira','statusOnHit','stun');source.statuses=[];const current=skillStatusOnHitChance(source,sk,'stun');applyStatus(source,'stunFocus',source,{duration:1,force:true});const next=skillStatusOnHitChance(source,{name:'Attack'},'stun');return sk.doublesStunChance&&current===Math.min(.95,base*2)&&next===Math.min(.95,base*2)&&statusOf(source,'stunFocus').remaining===1;})()`);
check('Every damaging Mira skill adds half AGI to its primary offense stat', `(() => {const stats=totals('Mira'),unit={id:'Mira',statuses:[]};return battleSkills('Mira',unit).filter(skillTargetsEnemies).every(sk=>skillOffensiveStat('Mira',sk,unit,stats)===Math.round(stats[skillScaling(sk)]+stats.agi*.5))&&skillFormula(baseJobs.Mira.skills.find(sk=>sk.name==='Voidthorn Mark'),'Mira').includes('MAG + 0.5 AGI');})()`);
check('Silenced enemies are restricted to their basic physical action', `chooseEnemyAction.toString().includes('statusOf(unit, "silence")')&&chooseEnemyAction.toString().includes('enemyActionForKind(unit, "melee")')`);
check('Torren grants party Vampiric and Sparky grants a stronger single-ally version', `(() => {const stew=baseJobs.Torren.skills.find(skillEntry=>skillEntry.name==='Hearty Red Stew'),ember=baseJobs.Sparky.skills.find(skillEntry=>skillEntry.name==='Emberblood');return STATUS_DEFS.vampiric.duration===3&&stew?.targetSide==='party'&&stew.partyWide&&stew.buffs?.[0]?.type==='vampiric'&&stew.buffs[0].value===.2&&stew.buffs[0].duration===3&&ember?.targetSide==='ally'&&ember.buffs?.[0]?.type==='vampiric'&&ember.buffs[0].value===.25&&ember.buffs[0].duration===3;})()`);
check('Vampiric recovery uses direct damage and the active buff percentage', `useSkill.toString().includes('directDamageDealt += dmg')&&useSkill.toString().includes('statusValue(u, "vampiric")')&&useSkill.toString().includes('directDamageDealt * vampiric')`);
check('Single-ally support skills use the existing living-ally target picker', `chooseSkillTarget.toString().includes('sk.targetSide === "ally"')&&renderBattleTargets.toString().includes('battle.party.filter(ally => ally.hp > 0)')&&useSkill.toString().includes('sk.targetSide === "ally"')`);
check('Gear search indexes names, rarity, effects, statuses and rolled affixes', `(() => {const source=gearSearchText.toString();return ['gearDisplayName','gearRarity','gearEffects','entry.status','entry.element','formatAffix'].every(token=>source.includes(token));})()`);
check('Gear filtering combines search, slot, rarity, usability, equipment and affix matching', `(() => {const source=filteredSortedGear.toString();return ['gearSearchText','gearBrowser.slot','gearBrowser.rarity','canEquip','gearBrowser.equipped','gearBrowser.affixes','matches.every','matches.some'].every(token=>source.includes(token));})()`);
check('Gear sorting exposes requested stats plus numerical selected-affix strength', `GEAR_SORT_FIELDS.map(entry=>entry[0]).join(',')==='newest,name,itemPower,rarity,affixCount,str,agi,mag,def,hp,mp,crit,speed'&&gearAffixFacet({type:'statPct',stat:'mag'}).key==='statPct:mag'&&gearAffixFacet({type:'statusOnHit',status:'stun'}).key==='status:stun'&&gearAffixFacetValue.toString().includes('Math.max(...values)')&&gearBrowserToolbarHtml.toString().includes('selectedAffixSorts.map')`);
check('Gear controls separate fixed stats from affixes and reset both', `gearBrowserToolbarHtml.toString().includes('placeholder="Search gear..."')&&gearBrowserToolbarHtml.toString().includes('data-gear-stat="')&&gearBrowserToolbarHtml.toString().includes('data-gear-match="any"')&&gearBrowserToolbarHtml.toString().includes('data-gear-match="all"')&&bindGearBrowserControls.toString().includes('search.oninput')&&resetGearBrowser.toString().includes('stats: []')&&resetGearBrowser.toString().includes('affixes: []')`);
check('Fixed MAG filtering includes non-weapons and excludes MAG-affix-only gear', `(() => {const oldAffixes=structuredClone(state.gearAffixes),oldBrowser=structuredClone(gearBrowser);try {state.gearAffixes['Flameguard Plate']=[{label:"Scholar's",type:'statPct',stat:'mag',value:.15}];Object.assign(gearBrowser,{search:'',stats:['mag'],statMatch:'any',affixes:[],affixMatch:'any',slot:'all',rarity:'all',usability:'all',equipped:'all',sort:'mag',direction:'desc'});const entries=['Cinder Star','Workshop Coat','Flameguard Plate','Voice of Verse'].map(ref=>({ref,gear:gearByName(ref)}));return filteredSortedGear(entries).map(entry=>entry.ref).join(',')==='Voice of Verse,Cinder Star,Workshop Coat';}finally {state.gearAffixes=oldAffixes;Object.assign(gearBrowser,oldBrowser);}})()`);
check('Selecting a fixed stat sorts that stat highest first instead of newest', `gearSortForStat('mag')==='mag'&&gearSortForStat('stam')==='def'&&bindGearBrowserControls.toString().includes('gearBrowser.sort = gearSortForStat')`);
check('Combined gear filters sort actual stored Stun rolls from strongest to weakest', `(() => {const oldAffixes=structuredClone(state.gearAffixes),oldRarities={...state.gearRarities},oldBrowser=structuredClone(gearBrowser);try {state.gearAffixes['Guildsteel Saber']=[{label:'Fleet',type:'statPct',stat:'agi',value:.1},{label:'Stormbreaking',type:'statusOnHit',status:'stun',value:.05}];state.gearAffixes['Ember Pike']=[{label:'Fleet',type:'statPct',stat:'agi',value:.12},{label:'Stormbreaking',type:'statusOnHit',status:'stun',value:.08}];state.gearAffixes['Shelter Staff']=[{label:'Fleet',type:'statPct',stat:'agi',value:.14},{label:'Stormbreaking',type:'statusOnHit',status:'stun',value:.06}];state.gearRarities['Guildsteel Saber']='Epic';state.gearRarities['Ember Pike']='Epic';state.gearRarities['Shelter Staff']='Rare';Object.assign(gearBrowser,{search:'stun',stats:[],affixes:['statPct:agi'],affixMatch:'all',slot:'weapon',rarity:'Epic',usability:'all',equipped:'all',sort:'affix:status:stun',direction:'desc'});const entries=['Guildsteel Saber','Ember Pike','Shelter Staff'].map(ref=>({ref,gear:gearByName(ref)}));return filteredSortedGear(entries).map(entry=>entry.ref).join(',')==='Ember Pike,Guildsteel Saber';}finally {state.gearAffixes=oldAffixes;state.gearRarities=oldRarities;Object.assign(gearBrowser,oldBrowser);}})()`);
assert.ok(!htmlSource.includes('Rotate your device to play') && htmlSource.includes('data-control="cancel"'), 'Phone portrait remains playable and touch cancel exists');
assert.ok(!htmlSource.includes('data-control="party"') && !/>[PCZ]</.test(htmlSource), 'Touch controls do not expose keyboard letters');
assert.ok(cssSource.includes('html.touch-layout .battle:not(.hidden) .actions button') && cssSource.includes('min-height: 32px'), 'Combat commands have mobile tap targets');
assert.ok(cssSource.includes('html.touch-phone.touch-portrait .game') && cssSource.includes('env(safe-area-inset-left)'), 'Phone portrait gameplay and safe areas are mobile-scoped');
assert.ok(cssSource.includes('html:not(.touch-layout) .gamepad'), 'Small desktop windows do not receive touch controls');
assert.ok(cssSource.includes('html.touch-layout.touch-portrait:not(.touch-phone) .game'), 'Tablet portrait sizing remains touch-scoped');
assert.ok(cssSource.includes('html:not(.touch-layout).desktop-scaled .game'), 'Desktop game scaling remains isolated from touch layouts');
assert.ok(gameSource.includes('Math.ceil(rect.width / LOGICAL_WIDTH)'), 'Canvas resolution rounds up to preserve desktop image quality');
assert.ok(gameSource.includes('Available abilities (') && gameSource.includes('abilityUnlockLabel'), 'Status menu lists currently available abilities with level or talent origins');
check('Available abilities show scaling plus normal, critical, average and healing output', `(() => {const mira=statusAbilitiesHtml('Mira'),kael=statusAbilitiesHtml('Kael');return mira.includes('SCALING')&&mira.includes('STR')&&mira.includes('NORMAL')&&mira.includes('CRIT')&&mira.includes('AVG DPS')&&kael.includes('MAG')&&kael.includes('HPS');})()`);
check('Gear menu exposes per-hero and whole-roster optimization with both source modes', `(() => {const html=autoEquipToolbarHtml('Mira');return html.includes('data-auto-equip="hero"')&&html.includes('Optimize Mira')&&html.includes('data-auto-equip="party"')&&html.includes('Optimize everybody')&&html.includes('All gear')&&html.includes('Unequipped gear');})()`);
check('Whole-roster auto equip respects usability and owned copy limits', `(() => {const oldParty=[...state.party],oldGear=Object.fromEntries(Object.entries(baseJobs).map(([id,hero])=>[id,{...hero.gear}]));try {state.party=Object.keys(baseJobs);autoEquipParty('all');const refs=state.party.flatMap(id=>Object.values(baseJobs[id].gear).filter(Boolean));const valid=state.party.every(id=>Object.values(baseJobs[id].gear).every(ref=>!ref||canEquip(id,gearByName(ref))));const counts=refs.reduce((map,ref)=>(map[ref]=(map[ref]||0)+1,map),{});return valid&&Object.entries(counts).every(([ref,count])=>count<=gearCopyCount(ref));}finally {state.party=oldParty;Object.entries(oldGear).forEach(([id,gear])=>baseJobs[id].gear=gear);}})()`);
check('Unequipped-only optimization keeps gear worn by other heroes unavailable', `autoEquipHero.toString().includes('!token.equippedBy || token.equippedBy === id')&&autoEquipParty.toString().includes('choice.equippedBy !== id')`);
check('Zero HP plays DOWN once and only revive recovery clears it', `(() => {const unit={name:'Test Hero',hp:0,max:100,anim:'idle',guarding:true};const fell=markBattleUnitDown(unit);const deathStarted=Number.isFinite(unit.deathTick);const firstDeathTick=unit.deathTick;const repeated=!markBattleUnitDown(unit)&&unit.deathTick===firstDeathTick;const stayedDown=unit.down&&unit.hp===0&&unit.anim==='death'&&!unit.guarding;const restored=reviveBattleUnit(unit,.35);return fell&&deathStarted&&repeated&&stayedDown&&restored===35&&!unit.down&&unit.anim==='idle'&&unit.deathTick===null;})()`);
assert.ok(gameSource.includes('BATTLE_DEATH_FRAME_TICKS = 8') && gameSource.includes('frame - (Number.isFinite(unit.deathTick) ? unit.deathTick : frame)') && gameSource.includes('if (deathAge < BATTLE_DEATH_FRAME_TICKS * 4) return;'), 'Party death sheets visibly play all five frames before showing DOWN and holding the final pose');
check('A full party wipe triggers defeat instead of the old automatic recovery', `!resolveEnemyTurn.toString().includes('Marla refuses a game over')&&resolveEnemyTurn.toString().includes('triggerPartyDefeat')&&triggerPartyDefeat.toString().includes('showBattleResult("defeat"')`);
check('Defeat returns Hall parties with full HP and MP without clearing a stage', `(() => {const oldMode=state.gameMode,oldParty=[...state.party],oldMap=state.map,oldProgress=structuredClone(state.hallBattles);try {state.gameMode='hallBattles';state.party=['Verseborn','Mira'];state.hallBattles={unlockedStage:7,clearedStages:[1,2,3,4,5,6],recruitStages:[3,6],pendingRecruit:0};baseJobs.Verseborn.hp=0;baseJobs.Verseborn.mp=0;baseJobs.Mira.hp=0;baseJobs.Mira.mp=0;returnAfterDefeat();return state.map==='emberHallBattles'&&state.hallBattles.unlockedStage===7&&state.hallBattles.clearedStages.length===6&&state.party.every(id=>baseJobs[id].hp===totals(id).max&&baseJobs[id].mp===totals(id).mp);}finally {state.gameMode=oldMode;state.party=oldParty;state.map=oldMap;state.hallBattles=oldProgress;}})()`);
check('Victory uses the result sheet with actual gold, drops, Resonance and EXP', `winBattle.toString().includes('showBattleResult("victory"')&&winBattle.toString().includes('rewards.drops.forEach')&&winBattle.toString().includes('label: "Gold"')&&winBattle.toString().includes('label: "EXP"')&&winBattle.toString().includes('label: "Resonance"')`);
assert.ok(htmlSource.includes('id="battleResult"') && htmlSource.includes('id="battleResultRewards"'), 'Battle result overlay is present');
assert.ok(cssSource.includes('.battle-result.is-victory') && cssSource.includes('.battle-result.is-defeat') && cssSource.includes('.hero-row.is-down'), 'Victory, defeat and DOWN presentation styles are present');
assert.ok(fs.existsSync(path.join(__dirname, '../public/game/assets/ui/battle-victory.png')) && fs.existsSync(path.join(__dirname, '../public/game/assets/ui/battle-defeat.png')), 'Supplied victory and defeat sheets are included');
assert.ok(gameSource.includes('Weakness included') && !gameSource.includes('Discover a weakness by hitting it or selecting a reveal talent.'), 'Battle command previews keep only compact decision information');
assert.ok(gameSource.includes('requestFullscreen') && htmlSource.includes('data-control="fullscreen"'), 'Touch layout exposes fullscreen where the browser supports it');
assert.ok(gameSource.includes('width=device-width, initial-scale=1, viewport-fit=cover') && !gameSource.includes('user-scalable=no'), 'Native pinch zoom remains available');
assert.ok(cssSource.includes('body[data-play-mode="battle"] .game') && cssSource.includes('height: calc(100dvh') && cssSource.includes('body[data-play-mode="battle"] .hud'), 'Landscape phone battles stay contained inside the usable viewport');
check('Touch layout requires touch points plus coarse non-hover input', `syncResponsiveDevice.toString().includes('navigator.maxTouchPoints')&&syncResponsiveDevice.toString().includes('(pointer: coarse)')&&syncResponsiveDevice.toString().includes('(hover: none)')`);
assert.ok(gameSource.includes('el.dialogue.addEventListener("click"') && gameSource.includes('if (mode === "talk") interact();'), 'Dialogue box taps advance only active dialogue');
console.log(`New combat/gear checks: ${passed}/${passed}`);
