const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const prefix = fs.readFileSync(path.join(__dirname, 'test_combat.cjs'), 'utf8')
  .split("run('runQaChecks()');")[0]
  .replace('sandbox.window = sandbox;', 'sandbox.fetch=async()=>({ok:false}); sandbox.window = sandbox;');
const {run} = new Function('require', '__dirname', `${prefix}\nreturn {run};`)(require, __dirname);
let passed = 0;
function check(name, code) {
  assert.ok(run(`(()=>{const random=Math.random;Math.random=()=>.999;try{return (${code});}finally{Math.random=random;}})()`), name);
  passed++;
  console.log('PASS', name);
}
run(`state.party=Object.keys(baseJobs);
 function setup(id, rank0=null, talents=[]) {
   state.heroProgress[id]={level:40,xp:0,talents,rank0};
   const u=battleUnit(id);u.hp=u.max;u.mp=u.maxmp=999;
   const ally={id:id==='Mira'?'Verseborn':'Mira',name:'Ally',hp:100,max:1000,mp:10,maxmp:20,statuses:[]};
   const other={id:'Torren',name:'Other',hp:100,max:1000,mp:10,maxmp:20,statuses:[]};
   const enemies=[0,1,2].map(n=>{const e=prepareEnemyForBattle(enemy('Probe'+n,99999,1,'None','#555',1));e.hp=e.max=99999;e.baseEvasion=0;return e;});
   battle={party:[u,ally,other],enemies,round:1,turnIndex:0,turnQueue:[{side:'party',id}],usedOnce:{},extraTurns:0,resolving:false,enemyResonance:80};
   mode='battle';battleFloaters=[];return {u,ally,other,foe:enemies[0],enemies};
 }
 function cast(u,name,target) {const sk=battleSkills(u.id,u).find(s=>s.name===name);if(!sk)throw Error('Missing '+name);battle.resolving=false;useSkill(u,sk,target);__impact();return sk;}
 function rawCast(u,sk,target) {battle.resolving=false;useSkill(u,sk,target);__impact();}
 function probe(element='Tech',extra={}) {return {name:'Probe',anim:'magic',element,power:0,cost:0,coefficient:1,...extra};}
 function enemyProbe(action, target, damage=100) {
   const choose=chooseEnemyAction,roll=enemyDamageRoll;
   try {
     chooseEnemyAction=()=>({...action,target});
     enemyDamageRoll=(e,a,d)=>({damage:Math.round(damage*incomingDamageMultiplier(d)),critical:false});
     battle.turnIndex=0;battle.turnQueue=[{side:'enemy',index:0}];battle.resolving=true;
     resolveEnemyTurn({side:'enemy',index:0},'');__impact();
   } finally {chooseEnemyAction=choose;enemyDamageRoll=roll;}
 }
`);
check('Three choices at Rank 0 and each paid tier; no new permanent actions', `Object.keys(baseJobs).every(id=>rank0Choices[id].length===3&&talentTrees[id].length===15&&[1,2,3,4,5].every(t=>talentTrees[id].filter(n=>n.tier===t).length===3))&&['Glimmer','Seerin','Sparky'].every(id=>talentTrees[id].every(n=>n.type!=='newSkill'))`);
check('Unaffected trees and Rank 0 options stay intact', `['Verseborn','Mira','Torren','Kael'].every(id=>talentTrees[id]===compactTalentTrees[id])&&rank0Choices.Kael.some(s=>s.name==='Quiet Tithe')&&rank0Choices.Torren.some(s=>s.name==='Hearty Red Stew')`);
check('Mira rename migrates saved selection without renaming Tier 4', `(()=>{state.heroProgress.Mira={level:40,talents:['Fade Into Shadow'],rank0:'Fade into Shadow'};return progressFor('Mira').rank0==='Veiled Recovery'&&progressFor('Mira').talents.includes('Fade Into Shadow')&&rank0Choices.Mira.find(s=>s.name==='Veiled Recovery').healScaling===.8;})()`);
check('Veiled Recovery heals exactly 25 + 0.8 MAG and gives two Evasion charges', `(()=>{const {u}=setup('Mira','Veiled Recovery');u.hp=1;const hp=u.hp,heal=Math.min(healingAmount('Mira',battleSkills('Mira').find(s=>s.rank0),u),u.max-1);cast(u,'Veiled Recovery',u);return u.hp-hp===heal&&statusOf(u,'evasion').value===.2&&statusOf(u,'evasion').incomingCharges===2;})()`);
check('Glimmer Rank 0 uses Combat Drone, never Support Drone or duplicate talent actions', `(()=>{const {u}=setup('Glimmer','Combat Drone');cast(u,'Combat Drone',u);return rank0Choices.Glimmer.map(s=>s.name).join('|')==='Patch Job|Combat Drone|Scramble Signal'&&statusOf(u,'combatDrone').value===.25&&statusOf(u,'combatDrone').remaining===99&&battleSkills('Glimmer').filter(s=>s.name==='Combat Drone').length===1;})()`);
check('Removed talents refund points, Rank 0 remains independent', `(()=>{state.heroProgress.Glimmer={level:40,talents:['Combat Drone','Arc Reactor','Patch Network'],rank0:'Patch Job'};const p=progressFor('Glimmer');return p.talents.join('|')==='Patch Network'&&p.rank0==='Patch Job'&&p.pendingMilestones.length===9;})()`);
check('Level-10 transformations remain second Ultimates lasting four actions', `['Glimmer','Kael'].every(id=>{const {u}=setup(id);progressFor(id).level=9;const before=!battleSkills(id).some(s=>s.transform);progressFor(id).level=10;const sk=battleSkills(id).find(s=>s.transform);activateTransformation(u,sk.transform);return before&&sk.ultimateIndex===2&&u.formTurns===4;})`);
check('Base kits retain their attacks, spells and starting Ultimates', `['Glimmer','Seerin','Sparky'].every(id=>{setup(id);return baseJobs[id].skills.filter(s=>s.name!==rank0MovedSkills[id]).every(s=>battleSkills(id).some(k=>k.name===s.name));})`);
check('Field Medic and Mobile Hospital increase only Patch Job healing', `(()=>{const {u}=setup('Glimmer','Patch Job');const sk=battleSkills('Glimmer').find(s=>s.rank0),base=healingAmount('Glimmer',sk,u);progressFor('Glimmer').talents=['Field Medic','Mobile Hospital'];return healingAmount('Glimmer',sk,u)===Math.round((Math.abs(sk.power)+totals('Glimmer').mag*.3)*1.35)&&healingAmount('Glimmer',sk,u)>base;})()`);
check('Patch Network heals all living allies and gives the existing two-action Drone', `(()=>{const {u,ally,other}=setup('Glimmer','Patch Job',['Patch Network']);cast(u,'Patch Job');return ally.hp>100&&other.hp>100&&[u,ally,other].every(a=>statusOf(a,'combatDrone').value===.4&&statusOf(a,'combatDrone').remaining===2);})()`);
check('Emergency Plating evaluates low HP independently per healed ally', `(()=>{const {u,ally,other}=setup('Glimmer','Patch Job',['Patch Network','Emergency Plating']);other.hp=800;cast(u,'Patch Job');return statusOf(ally,'barrier').value===.2&&statusOf(ally,'barrier').remaining===2&&!statusOf(other,'barrier')&&!statusOf(u,'barrier');})()`);
check('Overclocked Tools and Dual Drone apply potency and a half-damage second strike', `(()=>{const {u,enemies}=setup('Glimmer','Combat Drone',['Overclocked Tools','Dual Drone Protocol']);applyStatus(u,'combatDrone',u,{force:true,value:.25,duration:99});const expected=Math.round((totals('Glimmer').mag*.35+100*.15)*1.5);combatDroneFollowUp(u,100,1);return enemies[0].max-enemies[0].hp===expected&&enemies[1].max-enemies[1].hp===Math.round(expected*.5)&&enemies[2].hp===enemies[2].max;})()`);
check('Swarm adds exactly one 60% strike and can use another enemy', `(()=>{const {u,enemies}=setup('Glimmer','Combat Drone',['Dual Drone Protocol','Swarm Intelligence']);applyStatus(u,'combatDrone',u,{force:true,value:.25,duration:99});combatDroneFollowUp(u,100,1);const first=enemies[0].max-enemies[0].hp,second=enemies[1].max-enemies[1].hp;return second===Math.round(first*.5)+Math.round(first*.6)&&enemies[2].hp===enemies[2].max;})()`);
check('Reinforced Frame works only while a Drone is active', `(()=>{const {u}=setup('Glimmer',null,['Reinforced Frame']);const before=incomingDamageMultiplier(u);applyStatus(u,'combatDrone',u,{force:true});return Math.abs(incomingDamageMultiplier(u)-before*.85)<1e-8;})()`);
check('Dirty Wrench extends Scramble only; no direct damage or extra proc', `(()=>{const {u,foe}=setup('Glimmer','Scramble Signal',['Dirty Wrench','Disruptor Coil']);cast(u,'Scramble Signal',foe);return foe.hp===foe.max&&statusOf(foe,'disrupted').remaining===3&&statusOf(foe,'disrupted').value===.2;})()`);
check('Disruptor Coil applies the specified 15% direct-Tech debuff', `(()=>{const {u,foe}=setup('Glimmer',null,['Disruptor Coil']);Math.random=()=>.1;applySkillStatuses(u,foe,probe());return statusOf(foe,'disrupted').value===.15&&statusOf(foe,'disrupted').remaining===2;})()`);
check('Feedback Loop drains only once per AoE action; System Crash raises it to 20', `(()=>{const {u,enemies}=setup('Glimmer',null,['Feedback Loop','System Crash']);enemies.forEach(e=>applyStatus(e,'disrupted',u,{force:true,value:.2,duration:2}));rawCast(u,probe('Tech',{allEnemies:true}),enemies[0]);return battle.enemyResonance===84;})()`);
check('Feedback does not trigger from newly applied Disrupted on the same first hit', `(()=>{const {u,foe}=setup('Glimmer',null,['Feedback Loop','Disruptor Coil']);Math.random=()=>.1;rawCast(u,probe(),foe);return statusOf(foe,'disrupted')&&battle.enemyResonance>=88;})()`);
check('System Crash boosts only Tech against Disrupted enemies', `(()=>{const {u,foe}=setup('Glimmer',null,['System Crash']);applyStatus(foe,'disrupted',u,{force:true});return skillDamageTalentMultiplier(u,probe(),foe)===1.15&&skillDamageTalentMultiplier(u,probe('Sound'),foe)===1;})()`);
check('Carrier Chassis triggers without a persistent Drone, with Dual Protocol', `(()=>{const {u,enemies}=setup('Glimmer',null,['Carrier Chassis','Dual Drone Protocol']);u.form='mech';combatDroneFollowUp(u,100,1);return enemies[0].hp<enemies[0].max&&enemies[1].hp<enemies[1].max&&!statusOf(u,'combatDrone');})()`);
check('Mobile Clinic heals once per Mech action; Hospital gives low-HP Barrier', `(()=>{const {u,ally}=setup('Glimmer',null,['Mobile Clinic','Mobile Hospital']);u.form='mech';const hp=ally.hp;finishMechTalentAction(u);const once=ally.hp;finishMechTalentAction(u);return once-hp===Math.round(totals('Glimmer').mag*.4)&&ally.hp===once&&statusOf(ally,'barrier').value===.15&&statusOf(ally,'barrier').remaining===2;})()`);
check('EMP Array affects only primary target and refreshes duration', `(()=>{const {u,enemies}=setup('Glimmer',null,['EMP Array']);u.form='mech';rawCast(u,probe('Tech',{allEnemies:true}),enemies[1]);const primary=statusOf(enemies[1],'disrupted');const first=primary.value===.2&&primary.remaining===2&&!statusOf(enemies[0],'disrupted');primary.remaining=1;rawCast(u,probe(),enemies[1]);return first&&primary.remaining===2;})()`);
check('Radiant Brand upgrades Starflame Cut without adding an action', `(()=>{const {u,foe}=setup('Seerin',null,['Radiant Brand']);cast(u,'Starflame Cut',foe);return statusOf(foe,'holyVulnerability').value===.2&&statusOf(foe,'holyVulnerability').remaining===2&&!battleSkills('Seerin').some(s=>s.name==='Radiant Strike');})()`);
check('Shield Bash adds one Break only with Shieldbreaker and boosts Broken Attack', `(()=>{const {u,foe}=setup('Seerin','Shieldbreaker Oath',['Shield Bash']);const attack=battleSkills('Seerin').find(s=>s.basicAttack);applyStatus(foe,'broken',u,{force:true});const boosted=skillDamageTalentMultiplier(u,attack,foe)===1.2;progressFor('Seerin').rank0='Oathbreak';return attack.rank0Break===3&&boosted&&!battleSkills('Seerin').find(s=>s.basicAttack).rank0Break;})()`);
check('Sacred Constitution scales STAM for HP and adds MAG without changing STAM', `(()=>{setup('Seerin');const before=totals('Seerin');progressFor('Seerin').talents=['Sacred Constitution'];const after=totals('Seerin');return after.stam===before.stam&&after.mag===before.mag+Math.round(before.stam*.25)&&after.max>before.max;})()`);
check('Cinder Sanctuary gives every ally Holy Follow-up', `(()=>{const {u,ally,other}=setup('Seerin',null,['Cinder Sanctuary']);cast(u,'Cinder Guard');return [u,ally,other].every(a=>statusOf(a,'holyFollowUp').value===.1);})()`);
check('Purifying Oath cleanses once per qualifying AoE action', `(()=>{const {u,foe}=setup('Seerin',null,['Purifying Oath']);battle.enemyResonance=0;applyStatus(u,'poison',foe,{force:true});applyStatus(u,'burn',foe,{force:true});rawCast(u,probe('Holy Fire',{allEnemies:true}),foe);return ensureStatuses(u).filter(s=>STATUS_DEFS[s.type].negative).length===1;})()`);
check('Radiant Judgment dispels exactly one buff, drains 25 and grants Follow-up', `(()=>{const {u,foe}=setup('Seerin',null,['Radiant Judgment']);applyStatus(foe,'defenseUp',foe,{force:true});applyStatus(foe,'magicUp',foe,{force:true});cast(u,'Radiant Purge',foe);return ensureStatuses(foe).length===1&&battle.enemyResonance===55&&statusOf(u,'holyFollowUp').value===.15;})()`);
check('Bulwark protects only the chosen ally, once, and never AoE', `(()=>{const {u,ally,other}=setup('Seerin','Bulwark of Faith');cast(u,'Bulwark of Faith',ally);return statusOf(ally,'defenseUp').value===.25&&!statusOf(u,'defenseUp')&&!rank0Protector(other,false)&&!rank0Protector(ally,true)&&rank0Protector(ally,false)===u&&!rank0Protector(ally,false);})()`);
check('Hold the Line lasts until the start of Seerin next action', `(()=>{const {u,ally}=setup('Seerin','Bulwark of Faith',['Hold the Line']);cast(u,'Bulwark of Faith',ally);const taunt=u.holdTheLine;processTurnStart(u);return taunt&&!u.holdTheLine;})()`);
check('Protector strengthens Bulwark for critically wounded allies', `(()=>{const {u,ally}=setup('Seerin','Bulwark of Faith',['Protector']);cast(u,'Bulwark of Faith',ally);return Math.abs(statusOf(ally,'defenseUp').value-.2875)<1e-8;})()`);
check('Oathfire Ascendant upgrades the existing Ultimate and preserves Party Guard', `(()=>{const {u,foe}=setup('Seerin',null,['Oathfire Ascendant']);state.resonance=100;applyStatus(foe,'holyVulnerability',u,{force:true,value:.2,duration:2});const sk=battleSkills('Seerin').find(s=>s.anim==='ultimate');cast(u,sk.name,foe);return battle.enemyResonance===0&&battle.ward&&battleSkills('Seerin').filter(s=>s.anim==='ultimate').length===1;})()`);
check('Flameguard Charge keeps original Ultimate with Guard and primary-only +5 Break', `(()=>{const {u,enemies}=setup('Seerin',null,['Flameguard Charge']);state.resonance=100;const sk=battleSkills('Seerin').find(s=>s.anim==='ultimate');cast(u,sk.name,enemies[0]);return u.guarding&&battle.ward&&enemies[0].stagger===(enemies[1].stagger+5)%BREAK_THRESHOLD&&battleSkills('Seerin').filter(s=>s.anim==='ultimate').length===1;})()`);
check('Smolder extends Sparky Burn only, and Old Flame doubles tick only', `(()=>{const {u,foe}=setup('Sparky','Old Flame',['Smolder']);applyStatus(foe,'burn',u,{force:true,duration:4,value:10});const hp=foe.hp;processTurnStart(foe);return statusOf(foe,'burn').remaining===5&&statusOf(foe,'burn').value===10&&hp-foe.hp===20;})()`);
check('Shared Warmth adds Defense Up to Emberblood target only', `(()=>{const {u,ally}=setup('Sparky','Emberblood',['Shared Warmth']);cast(u,'Emberblood',ally);return statusOf(ally,'vampiric').value===.25&&statusOf(ally,'defenseUp').value===.1&&statusOf(ally,'defenseUp').remaining===3&&!statusOf(u,'defenseUp');})()`);
check('Tiny Dragon capstone intercepts three times only for chosen ally', `(()=>{const {u,ally,other}=setup('Sparky','Tiny Dragon, Big Problem',['Tiny Dragon, Huge Problem']);cast(u,'Tiny Dragon, Big Problem',ally);return statusOf(u,'defenseUp').value===.25&&!rank0Protector(other,false)&&[1,2,3].every(()=>rank0Protector(ally,false)===u)&&!rank0Protector(ally,false);})()`);
check('Successful intercept triggers Evasion, +12 Resonance and two-action Prrrp window', `(()=>{const {u,ally}=setup('Sparky','Tiny Dragon, Big Problem',['Smoke Trail','Brave Little Thing','Never Too Small']);cast(u,'Tiny Dragon, Big Problem',ally);const before=state.resonance;successfulSparkyIntercept(u);const sk=battleSkills('Sparky').find(s=>s.name==='Prrrp');const base={...u,prrrpWindow:0};return statusOf(u,'evasion').incomingCharges===1&&statusOf(u,'evasion').value===.3&&state.resonance===Math.min(100,before+12)&&u.prrrpWindow===2&&skillMpCost('Sparky',sk,u)===skillMpCost('Sparky',sk,base)-2&&healingAmount('Sparky',sk,u)>healingAmount('Sparky',sk,base);})()`);
check('Warm Little Heart increases Prrrp only; Ancient Comfort evaluates low HP', `(()=>{const {u,ally,other}=setup('Sparky',null,['Warm Little Heart','Ancient Comfort']);cast(u,'Prrrp');return statusOf(ally,'barrier').value===.2&&!statusOf(other,'barrier');})()`);
check('Ember Bite upgrades Ember Nip Burn without an extra action', `(()=>{const {u,foe}=setup('Sparky',null,['Ember Bite']);Math.random=()=>.1;cast(u,'Ember Nip',foe);return statusOf(foe,'burn').remaining===4&&!battleSkills('Sparky').some(s=>s.name==='Ember Bite');})()`);
check('Hungry Flame applies only to direct Ancient Fire against Burning enemies', `(()=>{const {u,foe}=setup('Sparky',null,['Hungry Flame']);applyStatus(foe,'burn',u,{force:true});return skillDamageTalentMultiplier(u,probe('Ancient Fire'),foe)===1.25&&skillDamageTalentMultiplier(u,probe('Sound'),foe)===1;})()`);
check('Inferno Heart refreshes applied full Burn duration without changing tick power', `(()=>{const {u,foe}=setup('Sparky',null,['Inferno Heart','Smolder']);applyStatus(foe,'burn',u,{force:true,duration:4,value:10});statusOf(foe,'burn').remaining=1;rawCast(u,probe('Ancient Fire'),foe);return statusOf(foe,'burn').remaining===5&&statusOf(foe,'burn').value===10;})()`);
check('Burn death transfer preserves duration, reduces stored potency and happens once', `(()=>{const {u,foe,enemies}=setup('Sparky','Old Flame',['Smolder','Living Wildfire']);applyStatus(foe,'burn',u,{force:true,duration:4,value:20});statusOf(foe,'burn').remaining=2;foe.hp=0;transferDeadSparkyBurns();const burn=statusOf(enemies[1],'burn');transferDeadSparkyBurns();const hp=enemies[1].hp;processTurnStart(enemies[1]);return burn.remaining===2&&burn.value===15&&hp-enemies[1].hp===30&&!statusOf(enemies[2],'burn');})()`);
check('Living Wildfire triggers from lethal Burn ticks too', `(()=>{const {u,foe,enemies}=setup('Sparky',null,['Living Wildfire']);applyStatus(foe,'burn',u,{force:true,duration:3,value:20});foe.hp=10;processTurnStart(foe);return foe.hp===0&&statusOf(enemies[1],'burn').value===15&&statusOf(enemies[1],'burn').remaining===3;})()`);
check('Ember Bond and Hearthfire scale from actual Vampiric HP restored', `(()=>{const {u,ally,other,foe}=setup('Sparky','Emberblood',['Ember Bond','Hearthfire']);u.hp=1;ally.hp=ally.max-4;other.hp=1;applyStatus(ally,'vampiric',u,{force:true,duration:3,value:.25});state.heroProgress.Mira={level:40,talents:[]};rawCast(ally,probe('Shadow'),foe);return ally.hp===ally.max&&u.hp===2&&other.hp===2;})()`);
check('Menu renders all replacement talents with one Rank 0 selected', `['Glimmer','Seerin','Sparky'].every(id=>{setup(id,rank0Choices[id][0].name);mode='menu';menuTab='skills';selectedSkillHero=id;renderMenu();return talentTrees[id].every(n=>el.menuBody.innerHTML.includes(n.name))&&!el.menuBody.innerHTML.includes('undefined')&&(rank0ChoicesHtml(id).match(/aria-pressed="true"/g)||[]).length===1;})`);
check('Hold the Line redirects real single-target damage but not AoE or enemy healing', `(()=>{const {u,ally,foe}=setup('Seerin','Bulwark of Faith',['Hold the Line']);cast(u,'Bulwark of Faith',ally);const hp=u.hp,ahp=ally.hp;enemyProbe({name:'Hit',kind:'melee',coefficient:1,element:'Physical'},ally);const single=u.hp<hp&&ally.hp===ahp;const before=ally.hp;enemyProbe({name:'Area',kind:'magic',coefficient:1,element:'Tech',allEnemies:true,allTargets:true},ally);const area=ally.hp<before;foe.hp=foe.max-1000;const fhp=foe.hp;enemyProbe({name:'Heal',kind:'magic',healing:true,healCoefficient:1},foe);return single&&area&&foe.hp>fhp;})()`);
check('Actual intercepted hit receives extra 15% reduction and triggers Sparky effects', `(()=>{const {u,ally}=setup('Sparky','Tiny Dragon, Big Problem',['Tough Little Scales','Smoke Trail','Brave Little Thing']);cast(u,'Tiny Dragon, Big Problem',ally);const hp=u.hp,ahp=ally.hp;state.resonance=0;enemyProbe({name:'Hit',kind:'melee',coefficient:1,element:'Physical'},ally);return hp-u.hp===Math.ceil(75*.85)&&ally.hp===ahp&&statusOf(u,'evasion').incomingCharges===1&&state.resonance===12;})()`);
check('Personal Guard triggers Retribution and Burning Aegis, each adding one Break', `(()=>{const {u,foe}=setup('Seerin',null,['Retribution','Burning Aegis']);u.guarding=true;const hp=foe.hp;enemyProbe({name:'Hit',kind:'melee',coefficient:1,element:'Physical'},u);return foe.hp<hp&&foe.stagger===2&&!u.guarding;})()`);
check('Party Guard alone does not trigger counters or reflection', `(()=>{const {u,foe}=setup('Seerin',null,['Retribution','Burning Aegis']);battle.ward=true;const hp=foe.hp;enemyProbe({name:'Hit',kind:'melee',coefficient:1,element:'Physical'},u);return foe.hp===hp&&foe.stagger===0;})()`);
check('Shield Discipline adds exactly twelve points to Personal Defend', `(()=>{const {u}=setup('Seerin');const before=defendReduction(u);progressFor('Seerin').talents=['Shield Discipline'];return defendReduction(u)===before+12;})()`);
check('Last Bastion prevents only one fatal hit in a battle', `(()=>{const {u,ally}=setup('Seerin',null,['Last Bastion']);enemyProbe({name:'Hit',kind:'melee',coefficient:1,element:'Physical'},ally,2000);const first=ally.hp===1;enemyProbe({name:'Hit',kind:'melee',coefficient:1,element:'Physical'},ally,2000);return first&&ally.hp===0&&battle.usedOnce['lastBastion:Seerin'];})()`);
console.log(`PASS ${passed}/${passed} focused talent-rework checks`);
