const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const prefix = fs.readFileSync(path.join(__dirname, 'test_combat.cjs'), 'utf8')
  .split("run('runQaChecks()');")[0]
  .replace('sandbox.window = sandbox;', 'sandbox.fetch=async()=>({ok:false}); sandbox.window = sandbox;');
const { run } = new Function('require', '__dirname', `${prefix}\nreturn {run};`)(require, __dirname);
let passed = 0;
function test(name, code) {
  assert.ok(run(`(() => {const previousRandom=Math.random; Math.random=()=>.999; try{return (${code});} finally{Math.random=previousRandom;}})()`), name);
  console.log(`PASS ${name}`);
  passed++;
}
run(`state.party=Object.keys(baseJobs); mode='menu'; menuTab='skills';
  function testBattle(id, talents=[], signature=null) {
    state.heroProgress[id]={level:40,xp:0,talents,signature};
    const u=battleUnit(id); u.mp=u.maxmp=999;
    const foe=prepareEnemyForBattle(enemy('Target',99999,1,'None','#555',1)); foe.hp=foe.max=99999;
    battle={party:[u],enemies:[foe],round:1,turnIndex:0,turnQueue:[{side:'party',id}],usedOnce:{},extraTurns:0,resolving:false,enemyResonance:100};
    battleFloaters=[]; mode='battle'; return {u,foe};
  }`);
test('Seven characters each have exactly three modest Signature choices', `Object.keys(baseJobs).every(id=>signatureAbilities[id].length===3&&new Set(signatureAbilities[id].map(s=>s.name)).size===3&&signatureAbilities[id].every(s=>s.signature&&s.anim!=='ultimate'&&s.cost<=6))`);
test('Legacy saves receive no automatic Signature and retain paid choices', `(() => {state.heroProgress.Verseborn={level:20,xp:15,talents:['Perfect Pitch','Battle Hymn']}; const p=progressFor('Verseborn');return !p.signature&&p.talents.join('|')==='Perfect Pitch|Battle Hymn'&&talentPointsSpent('Verseborn')===2;})()`);
test('Selecting and swapping Signature costs no point and never grants two', `(() => {mode='menu';selectedSkillHero='Verseborn';const before=JSON.stringify(progressFor('Verseborn').talents);selectSignature('Verseborn','Hush');selectSignature('Verseborn','Opening Verse');return progressFor('Verseborn').signature==='Opening Verse'&&JSON.stringify(progressFor('Verseborn').talents)===before&&battleSkills('Verseborn').filter(s=>s.signature).length===1;})()`);
test('Invalid selections and combat-time swaps are refused', `(() => {const before=progressFor('Verseborn').signature;mode='battle';const blocked=selectSignature('Verseborn','Hush');mode='menu';return !blocked&&!selectSignature('Verseborn','invalid')&&progressFor('Verseborn').signature===before;})()`);
test('Signature selection persists in the existing save payload', `(() => {mode='menu';const before=progressFor('Verseborn').signature;saveGame('talent-test');const data=JSON.parse(localStorage.getItem('talent-test'));state.heroProgress.Verseborn=structuredClone(data.state.heroProgress.Verseborn);return progressFor('Verseborn').signature===before;})()`);
test('Reset clears paid choices but preserves Signature', `(() => {mode='menu';const p=progressFor('Verseborn');const before=p.signature;resetTalents('Verseborn');return p.signature===before&&p.talents.length===0;})()`);
test('Tier 0 UI contains three cards, zero cost and selected state', `(() => {const html=signatureChoicesHtml('Verseborn');return (html.match(/data-signature=/g)||[]).length===3&&html.includes('0 talent points')&&(html.match(/aria-pressed="true"/g)||[]).length===1;})()`);
test('Existing five-tier progression and capstone payloads stay intact', `Object.values(talentTrees).every(tree=>tree.length===15&&[1,2,3,4,5].every(t=>tree.filter(n=>n.tier===t).length===3))&&JSON.stringify(TALENT_POINT_LEVELS)==='[4,8,12,16,20,24,28,32,36,40]'&&talentTrees.Seerin.find(t=>t.name==='Flameguard Charge').value.coefficient===2.7`);
test('Normal kits have one weapon, standard, Signature and starting Ultimate', `Object.keys(baseJobs).every(id=>{state.heroProgress[id]={level:1,xp:0,talents:[],signature:signatureAbilities[id][0].name};const kit=battleSkills(id);return kit.length===4&&kit.filter(s=>s.basicAttack).length===1&&kit.filter(s=>s.signature).length===1&&kit.filter(s=>s.anim==='ultimate').length===1;})`);
test('Only Kael and Glimmer unlock the unchanged transformation at level 10', `Object.keys(baseJobs).every(id=>{progressFor(id).level=9;const before=battleSkills(id);progressFor(id).level=10;const after=battleSkills(id);const transform=baseJobs[id].skills.find(s=>s.transform);return ['Kael','Glimmer'].includes(id)?before.length===4&&after.length===5&&after.filter(s=>s.anim==='ultimate').length===2&&JSON.stringify(after.find(s=>s.transform))===JSON.stringify(transform):after.length===4&&after.filter(s=>s.anim==='ultimate').length===1;})`);
test('All selectable talent combinations stay inside normal action limits', `Object.keys(baseJobs).every(id=>{const tree=talentTrees[id];return signatureAbilities[id].every(sig=>tree.filter(t=>t.tier===5).every(cap=>{state.heroProgress[id]={level:40,xp:0,signature:sig.name,talents:[...tree.filter(t=>t.tier<5).map(t=>t.name),cap.name]};const kit=battleSkills(id);return kit.length===(['Kael','Glimmer'].includes(id)?5:4)&&kit.filter(s=>s.signature).length===1&&kit.filter(s=>s.anim==='ultimate').length===(['Kael','Glimmer'].includes(id)?2:1);}))})`);
test('Hush does zero damage, Silences for one enemy action and expires', `(() => {const {u,foe}=testBattle('Verseborn',[],'Hush');useSkill(u,battleSkills(u.id).find(s=>s.signature),foe);__impact();const ok=foe.hp===foe.max&&statusOf(foe,'silence')?.remaining===1&&chooseEnemyAction(foe).kind==='melee';processTurnEnd(foe);return ok&&!statusOf(foe,'silence');})()`);
test('Verseborn Hushed Refrain baseline is one action', `baseJobs.Verseborn.skills.find(s=>s.name==='Hushed Refrain').status.duration===1`);
test('Quiet Seal suppresses gains and Ultimate for exactly one enemy action', `(() => {const {u,foe}=testBattle('Kael',[],'Quiet Seal');useSkill(u,battleSkills(u.id).find(s=>s.signature),foe);__impact();battle.enemyResonance=100;const ok=foe.hp===foe.max&&statusOf(foe,'resonanceLocked')?.remaining===1&&chooseEnemyAction(foe).kind!=='ultimate';const before=battle.enemyResonance;gainEnemyResonance(foe,10);processTurnEnd(foe);return ok&&before===battle.enemyResonance&&!statusOf(foe,'resonanceLocked')&&chooseEnemyAction(foe).kind==='ultimate';})()`);
test('Quiet Tithe retains one-action suppression baseline', `baseJobs.Kael.skills.find(s=>s.name==='Quiet Tithe').enemyResonanceLock===1`);
test('Torren preserves Heavy Hands without the redundant Basic Break stack', `!talentTrees.Torren.some(t=>t.type==='basicBreak')&&talentTrees.Torren.find(t=>t.name==='Concussive Blow').type==='guardCounter'&&talentTrees.Torren.find(t=>t.name==='Heavy Hands').type==='staggerBonus'&&talentTrees.Torren.find(t=>t.name==='Heavy Hands').value===1&&BREAK_THRESHOLD===3`);
test('Tier 0 protection stays single-ally without granting Party Guard', `(() => {const {u}=testBattle('Seerin',[],"Guardian's Oath");useSkill(u,battleSkills(u.id).find(s=>s.signature),u);__impact();return !battle.ward&&statusOf(u,'defenseUp')?.value===.12;})()`);
test('Seerin purification removes exactly one valid status, never Broken', `(() => {const {u}=testBattle('Seerin',[],'Cleansing Flame');u.statuses=[{type:'silence',remaining:1},{type:'poison',remaining:3},{type:'broken',remaining:1}];useSkill(u,battleSkills(u.id).find(s=>s.signature),u);__impact();return !statusOf(u,'silence')&&statusOf(u,'poison')&&statusOf(u,'broken');})()`);
test('Cleansing Flame talent protects immediately without removing a second status', `(() => {const {u}=testBattle('Seerin',['Cleansing Flame'],'Cleansing Flame');u.statuses=[{type:'silence',remaining:1},{type:'poison',remaining:3},{type:'broken',remaining:1}];useSkill(u,battleSkills(u.id).find(s=>s.signature),u);__impact();return statusOf(u,'poison')&&statusOf(u,'broken')&&statusOf(u,'barrier')?.value===.08;})()`);
test('Intercept is reliable once per round and ignores area attacks', `(() => {const {u}=testBattle('Seerin',['Intercept']);const ally={id:'Mira',name:'Mira',hp:20,max:100,statuses:[]};battle.party.push(ally);const first=protectiveInterceptor(ally,{kind:'melee'},battle.party);const second=protectiveInterceptor(ally,{kind:'melee'},battle.party);battle.round=2;const area=protectiveInterceptor(ally,{kind:'magic',allTargets:true},battle.party);return first===u&&!second&&!area&&protectiveInterceptor(ally,{kind:'melee'},battle.party)===u;})()`);
test('Protector triggers only on genuine danger crossing, once per round', `(() => {const {u}=testBattle('Seerin',['Protector']);const ally={id:'Mira',name:'Mira',hp:30,max:100,statuses:[]};battle.party.push(ally);const note=protectEndangeredAlly(ally,60);const first=statusOf(ally,'barrier')?.value;const repeated=protectEndangeredAlly(ally,60);return note&&first===.12&&!repeated&&!protectEndangeredAlly(ally,20);})()`);
test('Holy Retribution and Burning Aegis are restrained once-per-round reactions', `(() => {const {u,foe}=testBattle('Seerin',['Retribution','Burning Aegis']);const note=holyProtectionReaction(u,foe,{kind:'melee'});const damage=foe.max-foe.hp;holyProtectionReaction(u,foe,{kind:'melee'});const stats=totals(u.id);return note.includes('Retribution')&&damage===Math.max(1,Math.round((stats.str+stats.mag*.5)*.25))&&foe.max-foe.hp===damage&&u.aegisRound===1;})()`);
test('Hungry Flame refreshes an existing Sparky Burn without increasing tick damage', `(() => {const {u,foe}=testBattle('Sparky',['Hungry Flame'],'Ancient Spark');applyStatus(foe,'burn',u,{force:true,duration:1,value:7});useSkill(u,battleSkills(u.id).find(s=>s.signature),foe);__impact();return statusOf(foe,'burn')?.remaining===2&&statusOf(foe,'burn').value===7;})()`);
test('Inferno Heart spreads a half-strength Burn only once per battle', `(() => {const {u,foe}=testBattle('Sparky',['Inferno Heart'],'Ancient Spark');applyStatus(foe,'burn',u,{force:true,duration:3,value:10});const other=prepareEnemyForBattle(enemy('Other',99999,1,'None','#555',1));other.hp=other.max=99999;battle.enemies.push(other);useSkill(u,battleSkills(u.id).find(s=>s.signature),foe);__impact();const first=statusOf(other,'burn');const third={...other,name:'Third',statuses:[]};battle.enemies.push(third);battle.resolving=false;useSkill(u,battleSkills(u.id).find(s=>s.signature),foe);__impact();return first?.value===5&&first.remaining===2&&!statusOf(third,'burn');})()`);
test('Smoke Trail has a deterministic defensive and MP payoff', `(() => {const {u,foe}=testBattle('Sparky',['Smoke Trail'],'Ancient Spark');useSkill(u,battleSkills(u.id).find(s=>s.signature),foe);__impact();const evasion=statusOf(u,'evasion');u.mp=0;const dodged=tryEvadeAttack(u,0);return evasion?.value===.15&&evasion.incomingCharges===0&&dodged&&u.mp===Math.round(u.maxmp*.03);})()`);
test('Ancient Spark uses a modest ECHO contribution', `(() => {const s=signatureAbilities.Sparky.find(s=>s.name==='Ancient Spark');const t={str:0,mag:100,stam:0,agi:0,echo:40};return skillOffensiveStat('Sparky',s,{id:'Sparky'},t)===106&&s.coefficient===.6;})()`);
test('Baseline Burn setup uses small coefficients, not the full Burn tick', `(() => {const {u,foe}=testBattle('Sparky',[],'Ember Bite');return dotValueFor('burn',foe,u,{coefficient:.1,scaling:'str'})<dotValueFor('burn',foe,u,{scaling:'str'});})()`);
test('Minor Pocket Drone fires only once; full talent Drone has no charge limit', `(() => {const {u,foe}=testBattle('Glimmer',[],'Pocket Drone');useSkill(u,battleSkills(u.id).find(s=>s.signature),u);__impact();const charges=statusOf(u,'combatDrone')?.assistCharges;battle.resolving=false;useSkill(u,battleSkills(u.id)[0],foe);__impact();const expired=!statusOf(u,'combatDrone');progressFor(u.id).talents=['Combat Drone'];battle.resolving=false;useSkill(u,battleSkills(u.id).find(s=>s.signature),u);__impact();return charges===1&&expired&&!statusOf(u,'combatDrone').assistCharges&&statusOf(u,'combatDrone').remaining===99;})()`);
test('Every baseline Signature resolves safely on its intended target and pays MP', `(() => {const random=Math.random;Math.random=()=>0;try{return Object.keys(signatureAbilities).every(id=>signatureAbilities[id].every(signature=>{const {u,foe}=testBattle(id,[],signature.name);const sk=battleSkills(id).find(s=>s.signature);const target=skillTargetsEnemies(sk)?foe:u;u.hp=Math.floor(u.max*.5);const before=u.mp;const cost=skillMpCost(id,sk,u);useSkill(u,sk,target);__impact();return !battle.attackDamage&&u.mp===before-cost&&(sk.statusOnly?foe.hp===foe.max:true);}));}finally{Math.random=random;}})()`);
test('Gentle Rite heals the selected ally rather than a different wounded ally', `(() => {const random=Math.random;Math.random=()=>.999;try{const {u}=testBattle('Kael',[],'Gentle Rite');const selected={id:'Mira',name:'Mira',hp:50,max:100,statuses:[]};const wounded={id:'Torren',name:'Torren',hp:1,max:100,statuses:[]};battle.party.push(selected,wounded);useSkill(u,battleSkills(u.id).find(s=>s.signature),selected);__impact();return selected.hp>50&&wounded.hp===1;}finally{Math.random=random;}})()`);
test('Unbroken Line adds its protection once, not once per stacked buff', `(() => {const {u}=testBattle('Seerin',['Unbroken Line']);const ally={id:'Mira',statuses:[]};applyStatus(ally,'barrier',u,{force:true,value:.1,duration:2});applyStatus(ally,'defenseUp',u,{force:true,value:.1,duration:2});return Math.abs(incomingDamageMultiplier(ally)-.65)<.00001;})()`);
console.log(`PASS ${passed}/${passed} focused talent cleanup checks`);
if (process.argv.includes('--fixture')) {
  const dir = path.join(__dirname, '../.sites-artifacts/talent-cleanup-qa');
  fs.mkdirSync(dir, { recursive: true });
  run(`mode='menu';menuTab='skills';selectedSkillHero='Seerin';state.party=Object.keys(baseJobs);progressFor('Seerin').signature="Guardian's Oath";renderMenu();`);
  const menu = run('el.menuBody.innerHTML').replaceAll('src="assets/', 'src="/public/game/assets/');
  fs.writeFileSync(path.join(dir, 'skills.html'), `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/public/game/styles.css"></head><body data-play-mode="menu"><section class="menu" data-menu-view="skills"><div class="menu-inner"><div class="menu-tabs"><button>Skills</button></div><div class="menu-body">${menu}</div></div></section></body></html>`);
}
