const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const prefix=fs.readFileSync(path.join(__dirname,'test_combat.cjs'),'utf8').split("run('runQaChecks()');")[0].replace('sandbox.window = sandbox;','sandbox.fetch=async()=>({ok:false}); sandbox.window=sandbox;');
const {run}=new Function('require','__dirname',prefix+'\nreturn {run};')(require,__dirname);
let checks=0;function check(name,code){assert.ok(run(code),name);console.log('PASS '+name);checks++;}
run(`state.inventory={};state.stash={};state.inventorySlots=10;state.bagUpgrades=0;state.gameMode='hallBattles';state.party=['Verseborn','Torren'];state.activeParty=state.party;`);
check('99 items use one slot, item 100 starts a second stack', `(()=>{addInventoryItem("Marla's Soup",99);if(inventoryUsed()!==1)return false;addInventoryItem("Marla's Soup");return inventoryUsed()===2;})()`);
check('Gear never uses inventory slots', `(()=>{const before=inventoryUsed();addOwnedGear('Courtesy Engine',1,{rarity:'Artifact',separateCopy:true});return inventoryUsed()===before;})()`);
check('Five collectibles each use their own stack slots', `(()=>{state.inventory={};HALL_COLLECTIBLES.forEach(name=>addInventoryItem(name,99));return HALL_COLLECTIBLES.length===5&&inventoryUsed()===5;})()`);
check('Full bag accepts an existing non-full stack, not a new type', `(()=>{state.inventory=Object.fromEntries(Array.from({length:10},(_,i)=>['item'+i,1]));return canCarryInventoryItem('item0')&&!canCarryInventoryItem('new');})()`);
check('Overflow goes to stash without loss', `(()=>{const ok=addInventoryItem('new',7);return !ok&&state.stash.new===7&&!state.inventory.new;})()`);
check('Legacy migration keeps every item and purchased upgrade', `(()=>{state.inventory=Object.fromEntries(Array.from({length:20},(_,i)=>['legacy'+i,99]));state.stash={};state.flags.inventoryStacksV1=false;state.bagUpgrades=1;migrateInventoryStacks();const total=Object.values(state.inventory).concat(Object.values(state.stash)).reduce((a,b)=>a+b,0);return state.inventorySlots===15&&inventoryUsed()===15&&total===1980;})()`);
check('Marla sells exactly four HP tiers, four MP tiers and revival', `['hp','mp'].every(type=>vendors.marla.wares.filter(w=>inventoryInfo(w.name).battle===type).length===4)&&vendors.marla.wares.some(w=>inventoryInfo(w.name).battle==='revive')`);
check('Potions scale to current maximum stats', `MARLA_CONSUMABLES.filter(w=>inventoryInfo(w.name).battle!=='revive').every(w=>consumableRecovery(inventoryInfo(w.name),1000)===inventoryInfo(w.name).fraction*1000)`);
check('All sixty Hall drops contain only usable supplies and five tokens', `(()=>{state.inventory={};state.stash={};state.inventorySlots=100;state.ngPlus=3;for(let stage=1;stage<=60;stage++){battle={hallStage:stage};const loot=rollBattleLoot([{name:'High Administrator Thaddeus'}],{hallStage:stage,allowGearLoot:false});if(!loot.drops.every(d=>inventoryInfo(d.name).battle||HALL_COLLECTIBLES.includes(d.name)))return false;const tier=Math.min(4,Math.ceil(stage/15));if(!['hp','mp'].every(type=>loot.drops.some(d=>inventoryInfo(d.name).battle===type&&inventoryInfo(d.name).tier===tier)))return false;}return true;})()`);
run(`updatePanels=()=>{};renderVendor=()=>{};queueSave=()=>{};finishTurn=()=>{};`);
check('Bag expansion adds five slots', `(()=>{activeVendor='marla';state.gold=1000;state.bagUpgrades=0;state.inventorySlots=10;buyWare(vendorWares(activeVendor).findIndex(w=>w.kind==='upgrade'));return state.inventorySlots===15&&state.bagUpgrades===1&&state.gold===860;})()`);
check('Full bag can purchase more of an existing stack', `(()=>{state.inventory=Object.fromEntries(Array.from({length:9},(_,i)=>['filler'+i,1]));state.inventory["Marla's Soup"]=1;state.inventorySlots=10;const before=state.gold;buyWare(vendorWares('marla').findIndex(w=>w.name==="Marla's Soup"));return state.inventory["Marla's Soup"]===2&&state.gold===before-18&&inventoryUsed()===10;})()`);
check('Revival consumes one item and revives selected ally only', `(()=>{state.inventory={'Phoenix Ticket':2};const actor={id:'Verseborn',name:'Verseborn',hp:100,max:100,mp:50,maxmp:50,statuses:[]},fallen={id:'Torren',name:'Torren',hp:0,max:1000,mp:0,maxmp:50,down:true,statuses:[],deathTick:12};battle={party:[actor,fallen],resolving:false};useBattleItem(actor,'Phoenix Ticket',fallen);return fallen.hp===500&&!fallen.down&&fallen.deathTick===null&&actor.hp===100&&state.inventory['Phoenix Ticket']===1;})()`);
console.log('PASS '+checks+'/'+checks+' inventory, consumables and Hall drop checks');
