const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const prefix = fs.readFileSync(path.join(__dirname, 'test_combat.cjs'), 'utf8').split("run('runQaChecks()');")[0]
  .replace('sandbox.window = sandbox;', 'sandbox.fetch=async()=>({ok:false}); sandbox.window = sandbox;');
const { run } = new Function('require', '__dirname', prefix + '\nreturn {run};')(require, __dirname);
let passed = 0;
function check(name, code) { assert.ok(run(code), name); console.log('PASS ' + name); passed++; }
run(`function endSetup(stage) {
  state.party=['Verseborn','Mira','Seerin']; state.activeParty=state.party; state.gameMode='hallBattles';
  state.party.forEach(id=>state.heroProgress[id]={level:40,xp:0,talents:[],rank0:rank0Choices[id][0].name});
  const info=hallBattleInfo(stage),enemies=hallEnemiesForStage(stage,info.waves[1],2).map(source=>prepareEnemyForBattle(source));
  battle={party:state.party.map(battleUnit),enemies,hallStage:stage,enemyResonance:0,defeated:[],usedOnce:{},round:1,turnQueue:[],turnIndex:0,extraTurns:0,resolving:false};
  battle.party.forEach(u=>{u.hp=u.max=50000;u.mp=u.maxmp=999;u.baseEvasion=0;});
  enemies.forEach(e=>{e.hp=e.max=50000;e.baseEvasion=0;if(e.endgameBoss)endgameMechanicState(e);});mode='battle';
  return {e:enemies[0],ally:enemies[1],u:battle.party[0],other:battle.party[1]};
}
function endAction(e) { const a=endgameEnemyAction(e); if(a.endgameEffect)endgameResolveEnemyEffect(e,a,a.target); e.actionsTaken=(e.actionsTaken||0)+1; return a; }
`);
check('Sixty stages; all new stages have exactly three phases', `HALL_BATTLE_BLUEPRINTS.length===60&&HALL_BATTLE_BLUEPRINTS.slice(50).every(b=>b.waves.length===2&&[b.enemies,...b.waves].every(w=>w.length>=2&&w.length<=3&&w.every(k=>HALL_ENEMY_LIBRARY[k])))`);
check('New bosses are unique Phase 3 encounters only', `HALL_BATTLE_BLUEPRINTS.slice(50).every(b=>!b.enemies.concat(b.waves[0]).some(k=>ENDGAME_BOSS_CONFIG[HALL_ENEMY_LIBRARY[k].name])&&b.waves[1].filter(k=>ENDGAME_BOSS_CONFIG[HALL_ENEMY_LIBRARY[k].name]).length===1)&&new Set(HALL_BATTLE_BLUEPRINTS.slice(50).map(b=>b.waves[1][0])).size===10`);
check('Stage 56 retains Tja and Tibby in Phase 1', `hallBattleInfo(56).enemies.join(',')==='tja,tibby'`);
check('All sixty stage enemies prepare with valid animation keys', `HALL_BATTLE_BLUEPRINTS.every(b=>[b.enemies,...b.waves].every((keys,i)=>hallEnemiesForStage(b.stage,keys,i).map(e=>prepareEnemyForBattle(e)).every(e=>enemyAnimationKey(e)&&e.hp>0&&Number.isFinite(e.stats.mag))))`);
check('Completed Stage 50 saves unlock 51 without replay or data loss', `(()=>{const old={clearedStages:Array.from({length:50},(_,i)=>i+1),unlockedStage:50,shopStage:50,purchasedShopStages:[1,50],shopOffers:{50:{price:123}},startingWelcomeComplete:true};const next=normalizeHallBattleProgress(old);return next.unlockedStage===51&&next.clearedStages.length===50&&next.shopStage===50&&next.shopOffers[50].price===123&&next.purchasedShopStages.join(',')==='1,50';})()`);
check('New progression unlocks sequentially through 60', `(()=>{state.hallBattles={clearedStages:Array.from({length:50},(_,i)=>i+1),unlockedStage:50};for(let s=51;s<=60;s++){if(hallBattleProgress().unlockedStage!==s)return false;recordHallBattleClear(s);}return hallBattleProgress().clearedStages.length===60&&hallBattleProgress().unlockedStage===60;})()`);
check('Shops remain capped at 50 with their original rarity curve', `(()=>{state.hallBattles={clearedStages:[],unlockedStage:60,shopOffers:{},shopStage:0};const a=ensureHallShopOffer(50),b=ensureHallShopOffer(60);return JSON.stringify(a)===JSON.stringify(b)&&hallBattleProgress().shopStage===50&&!hallBattleProgress().shopOffers[51]&&hallShopGearRarity(41)==='Artifact'&&hallShopGearRarity(31)==='Mythic';})()`);
check('51-57 Mythic and 58-60 Artifact, existing tiers unchanged', `Array.from({length:60},(_,i)=>i+1).every(s=>rollHallGearRarity(s)===(s>=58?'Artifact':hallNormalGearRarity(s)))&&[51,57].every(s=>rollHallGearRarity(s)==='Mythic')`);
check('Generated endgame drops scale stats and retain affix metadata', `(()=>{state.gameMode='hallBattles';let seed=7;const old=Math.random;function seeded(){seed=(seed*16807)%2147483647;return seed/2147483647;}try{Math.random=seeded;const budgets=[50,51,57,58,60].map(s=>{seed=7;const r={drops:[],gearDrops:[]};const awarded=guaranteeHallBattleGearReward(r,s),g=gearInstance(awarded.ref);if(!g||g.affixes.some(a=>a.text!==formatAffix(a)))return 0;return Object.values(g.stats).reduce((a,b)=>a+b,0);});return budgets.every((n,i)=>n>0&&(!i||n>budgets[i-1]));}finally{Math.random=old;}})()`);
check('Veyr protection can be avoided and dispelled', `(()=>{const {e,ally,u}=endSetup(51);endAction(e);const sk=battleSkills(u.id,u)[0],before=u.hp;const safe=endgamePlayerDamageMultiplier(u,sk,e),penalty=endgamePlayerDamageMultiplier(u,sk,ally);const harmed=u.hp<before;enemyDispelOne(ally);return safe===1&&penalty<1&&harmed&&!statusOf(ally,'protectedGuest');})()`);
check('Maelin completes cleanse / barrier / strong healing, control interrupts', `(()=>{const {e,ally,u}=endSetup(52);applyStatus(ally,'poison',u,{force:true});const a=endAction(e),b=endAction(e),c=endgameEnemyAction(e);applyStatus(e,'silence',u,{force:true});const d=endgameEnemyAction(e);return a.endgameEffect==='sanctuaryCleanse'&&!statusOf(ally,'poison')&&b.endgameEffect==='sanctuaryWard'&&statusOf(ally,'barrier')&&c.healing&&c.allAllies&&c.healCoefficient===2&&d.kind==='melee'&&e.encounterMechanic.sanctuaryStep===0;})()`);
check('Voss rotates orders and escalates repeat violations', `(()=>{const {e,u}=endSetup(53);endAction(e);const sk=battleSkills(u.id,u)[0];endgameInspectPlayerAction(u,sk,e,sk.name);endgameInspectPlayerAction(u,sk,e,sk.name);endgameInspectPlayerAction(u,sk,e,sk.name);const stamped=statusValue(u,'violationStamp')===3&&statusOf(u,'silence');e.encounterMechanic.order=null;const next=endAction(e);return stamped&&next.endgameEffect==='order'&&e.encounterMechanic.order.type==='buff';})()`);
check('Guidance marks move, telegraph impact and are cleanseable', `(()=>{const {e,u}=endSetup(54);endAction(e);const first=e.encounterMechanic.pending;endAction(e);const second=e.encounterMechanic.pending,hit=endgameEnemyAction(e);return first!==second&&hit.target===second&&hit.coefficient===2.1&&!statusOf(first,'guidanceMark')&&!statusOf(second,'guidanceMark');})()`);
check('Cleansing Guidance cancels its pending strike', `(()=>{const {e}=endSetup(54);endAction(e);const t=e.encounterMechanic.pending;enemyCleanseOne(t);return endgameEnemyAction(e).endgameEffect==='mark';})()`);
check('Guardian adapts to repeated categories; core and Break create burst', `(()=>{const {e,u}=endSetup(55);const sk=battleSkills(u.id,u)[0],first=endgamePlayerDamageMultiplier(u,sk,e),second=endgamePlayerDamageMultiplier(u,sk,e);const magic={...sk,anim:'magic',scaling:'mag'},changed=endgamePlayerDamageMultiplier(u,magic,e);endgameBossBroken(e);return first===1&&second<1&&changed===1&&endgamePlayerDamageMultiplier(u,sk,e)===1.6&&e.breakThreshold===BREAK_THRESHOLD*3;})()`);
check('Guardian adaptation expires after its own combat window', `(()=>{const {e,u}=endSetup(55);endgamePlayerDamageMultiplier(u,battleSkills(u.id,u)[0],e);endgameBossTurnStart(e);endgameBossTurnStart(e);return !statusOf(e,'memoryAdaptation')&&e.encounterMechanic.adaptation===0;})()`);
check('Malkhius copies buffs without transforming and delays attacks', `(()=>{const {e,u}=endSetup(56);applyStatus(u,'magicUp',u,{force:true,value:.3});endAction(e);const copied=statusValue(e,'magicUp')===.3;endAction(e);const a=endgameEnemyAction(e);return copied&&!e.form&&a.name==='Delayed Occult Echo'&&a.target===battle.party[1];})()`);
check('Morvanna misdirects until cleansed and inverts buffs', `(()=>{const {e,u,ally}=endSetup(57);endAction(e);const sk=battleSkills(u.id,u)[0],redirect=endgamePlayerTarget(u,sk,e)!==e;enemyCleanseOne(u);const clean=endgamePlayerTarget(u,sk,e)===e;applyStatus(u,'magicUp',u,{force:true});endAction(e);return redirect&&clean&&!statusOf(u,'magicUp')&&statusOf(u,'magicDefenseDown');})()`);
check('Oathguard taunts, Break opens shield and failed window strengthens it', `(()=>{const {e,u,ally}=endSetup(58);endAction(e);const sk=battleSkills(u.id,u)[0],forced=endgamePlayerTarget(u,sk,ally)===e,shield=endgamePlayerDamageMultiplier(u,sk,e);endgameBossBroken(e);const open=endgamePlayerDamageMultiplier(u,sk,e);endgameBossTurnStart(e);endgameBossTurnStart(e);endgameBossTurnStart(e);return forced&&shield===.4&&open===1.75&&statusValue(e,'oathguard')>.6&&!statusOf(e,'brokenOath');})()`);
check('Crescendo is telegraphed and interruption removes its rings', `(()=>{const {e,u}=endSetup(59);endAction(e);endAction(e);endAction(e);const charge=endgameEnemyAction(e);endgameResolveEnemyEffect(e,charge,e);const ready=e.encounterMechanic.charging;applyStatus(e,'silence',u,{force:true});const stopped=endgameEnemyAction(e);return ready&&charge.endgameEffect==='charge'&&stopped.kind==='melee'&&!statusOf(e,'harmonicRings')&&!e.encounterMechanic.charging;})()`);
check('Defeating Cantor support limits ring power', `(()=>{const {e}=endSetup(59);endgameResolveEnemyEffect(e,{endgameEffect:'rings'},e);endgameResolveEnemyEffect(e,{endgameEffect:'rings'},e);battle.enemies.slice(1).forEach(a=>a.hp=0);endgameBossTurnStart(e);return e.encounterMechanic.rings===0&&!statusOf(e,'harmonicRings');})()`);
check('Living Archive removes, stores and transfers a buff', `(()=>{const {e,u,ally}=endSetup(60);applyStatus(u,'barrier',u,{force:true,value:.3});endAction(e);const captured=!statusOf(u,'barrier')&&e.encounterMechanic.record.kind==='Buff Record';endAction(e);return captured&&statusValue(ally,'barrier')===.3&&!e.encounterMechanic.record;})()`);
check('Skill Records block only recorded skill without spending MP', `(()=>{const {e,u}=endSetup(60);e.encounterMechanic.recordIndex=1;u.lastActiveSkill=battleSkills(u.id,u).find(s=>s.cost>0&&s.anim!=='ultimate').name;endAction(e);const sk=battleSkills(u.id,u).find(s=>s.name===u.lastActiveSkill),before=u.mp;useSkill(u,sk,e);return u.mp===before&&!battle.resolving&&statusOf(u,'skillRecord').skillName===sk.name&&CLEANSE_PRIORITY.skillRecord>0;})()`);
check('New mechanics reuse existing icon mappings only', `Object.keys(ENDGAME_BOSS_CONFIG).length===10&&['guidanceMark','beguilingVeil','skillRecord','harmonicRings','oathguard'].every(type=>STATUS_DEFS[type]&&statusIconAliases[type]&&STATUS_DEFS[statusIconAliases[type]])`);
check('Every new boss resolves its actual first enemy action', `(()=>{for(let stage=51;stage<=60;stage++){const {e}=endSetup(stage);resolveEnemyTurn({side:'enemy',index:0},'');__impact();if(e.actionsTaken!==1||!battle.lastAttackDamage)return false;}return true;})()`);
const manifest = JSON.parse(fs.readFileSync(path.join(__dirname, '../public/game/assets/sprites/enemies-battle/manifest.json')));
check('Every new boss avoids the opaque generic projectile fallback', `(()=>{for(let s=51;s<=60;s++){const {e,u}=endSetup(s);for(const kind of ['melee','magic','ultimate','buff','utility','cleanse']){const fx=makeEnemyBattleEffect(e,kind==='buff'?e:u,{kind,name:'Visual test'});if(!fx.bossSheetVfx)return false;effect=fx;drawEffect();effect.startedAt-=fx.timing.totalMs;drawEffect();if(effect)return false;}}return true;})()`);
check('Dedicated VFX select all four rows and actual support targets', `(()=>{for(let s=51;s<=60;s++){const {e,u,ally}=endSetup(s);for(const [kind,row] of [['melee','melee'],['magic','magic'],['ultimate','ultimate'],['buff','support'],['cleanse','support'],['utility','support']]){const fx=makeEnemyBattleEffect(e,kind==='buff'?ally:u,{kind,name:'Visual test'});if(fx.vfxKind!==row)return false;if(kind==='buff'&&fx.vfxTargets[0].x!==enemyBattlePosition(1,battle.enemies.length)[0])return false;}}return true;})()`);
check('Protected Guest VFX follow the current guest and Sanctuary covers all allies', `(()=>{let {e,u,ally}=endSetup(51);e.encounterMechanic.guestIndex=1;const fx=makeEnemyBattleEffect(e,e,{kind:'utility',endgameEffect:'guest'});if(fx.vfxTargets[0].x!==enemyBattlePosition(2,3)[0])return false;({e,u}=endSetup(52));return makeEnemyBattleEffect(e,e,{kind:'magic',healing:true,allAllies:true}).vfxTargets.length===3;})()`);
check('Cantor can release a charged attack after losing all support', `(()=>{const {e}=endSetup(59);e.encounterMechanic.charging=true;e.encounterMechanic.rings=0;return endgameEnemyAction(e).kind==='ultimate'&&!e.encounterMechanic.charging;})()`);
check('Endgame Silence blocks magic without spending MP', `(()=>{const {e,u}=endSetup(53);applyStatus(u,'silence',e,{force:true});const sk=battleSkills(u.id,u).find(s=>s.anim==='magic');const mp=u.mp;useSkill(u,sk,e);return endgameSilenceBlocks(u,sk)&&!endgameSilenceBlocks(u,{anim:'melee'})&&u.mp===mp&&!battle.resolving;})()`);
check('Archive displays the correct Skill Record on the boss', `(()=>{const {e,u}=endSetup(60);e.encounterMechanic.recordIndex=1;u.lastActiveSkill='Resonant Verse';endAction(e);const shown=!!statusOf(e,'skillRecord');endAction(e);return shown&&!statusOf(e,'skillRecord')&&!!statusOf(u,'skillRecord');})()`);
const names = run(`Object.values(enemyAnimationFiles)`);
for (const name of new Set(names)) {
  assert.ok(manifest[name], 'Missing mapping ' + name);
  assert.ok(fs.existsSync(path.join(__dirname, '../public/game/assets/sprites/enemies-battle', manifest[name].file)), 'Missing file ' + name);
}
console.log('PASS '+passed+'/'+passed+' focused endgame checks; all active enemy mappings resolve');
