const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const prefix = fs.readFileSync(path.join(__dirname, 'test_combat.cjs'), 'utf8').split("run('runQaChecks()');")[0]
  .replace('sandbox.window = sandbox;', 'sandbox.fetch=async()=>({ok:false}); sandbox.window = sandbox;');
const { run } = new Function('require', '__dirname', prefix + '\nreturn {run};')(require, __dirname);
function check(name, code) { assert.ok(run(code), name); console.log('PASS ' + name); }
run(`state.gameMode='hallBattles';state.party=['Verseborn','Torren','Glimmer'];state.activeParty=state.party;state.hallBattles={clearedStages:Array.from({length:50},(_,i)=>i+1),unlockedStage:50};`);
check('Stage 50 save has no Artifact commissions', `hallBattleProgress().unlockedStage===51&&glimmerArtifactWares().length===0`);
check('Each clear unlocks exactly one persistent commission', `(()=>{for(let stage=51;stage<=60;stage++){recordHallBattleClear(stage);if(glimmerArtifactWares().length!==stage-50)return false;recordHallBattleClear(stage);}return hallBattleProgress().artifactShopUnlocks.length===10;})()`);
check('Unlocked stage alone does not unlock a commission', `glimmerArtifactWares().length===10&&normalizeHallBattleProgress({unlockedStage:60}).artifactShopUnlocks.length===0`);
check('Unlocks survive serialization and old completed saves migrate', `(()=>{const saved=JSON.parse(JSON.stringify(state.hallBattles));return normalizeHallBattleProgress(saved).artifactShopUnlocks.length===10&&normalizeHallBattleProgress({clearedStages:[50,51,52]}).artifactShopUnlocks.join(',')==='51,52';})()`);
check('Other vendor inventories remain unchanged', `Object.keys(vendors).filter(id=>id!=='workshop').every(id=>JSON.stringify(vendorWares(id))===JSON.stringify(vendors[id].wares))`);
check('Ten unique named Artifacts, distinct from boss trophies', `GLIMMER_ARTIFACT_CATALOG.length===10&&new Set(GLIMMER_ARTIFACT_CATALOG.map(e=>e.gear.name)).size===10&&GLIMMER_ARTIFACT_CATALOG.every(e=>defaultGearRarity(e.gear.name)==='Artifact'&&!HALL_ARTIFACT_GEAR.some(g=>g.name===e.gear.name))`);
check('Fixed valid strong affixes and increasing prices', `glimmerArtifactWares().every((w,i,list)=>w.affixes.length===4&&w.affixes.every(a=>a.key&&a.value===a.max)&&w.price>=10000&&(!i||w.price>list[i-1].price)&&gearEffects(gearByName(w.name)).some(e=>e.artifactUnique))`);
check('Insufficient gold prevents purchase', `(()=>{activeVendor='workshop';state.gold=0;const before=JSON.stringify(state.ownedGear);buyWare(vendorWares('workshop').findIndex(w=>w.artifactShop));return state.gold===0&&before===JSON.stringify(state.ownedGear);})()`);
run(`renderVendor=()=>{};updatePanels=()=>{};queueSave=()=>{};`);
check('Purchase deducts exact price and preserves fixed stats and affixes', `(()=>{activeVendor='workshop';state.gold=999999;const wares=vendorWares(activeVendor),index=wares.findIndex(w=>w.artifactShop),ware=wares[index],before=state.gold;buyWare(index);const ref=ownedGearRefs().find(r=>gearByName(r)?.name===ware.name),instance=gearInstance(ref);return state.gold===before-ware.price&&instance&&instance.rarity==='Artifact'&&JSON.stringify(instance.stats)===JSON.stringify(ware.stats)&&instance.affixes.every((a,i)=>a.key===ware.affixes[i].key&&a.value===ware.affixes[i].value);})()`);
check('Commission remains available for additional separate copies', `(()=>{const index=vendorWares('workshop').findIndex(w=>w.artifactShop),ware=vendorWares('workshop')[index];buyWare(index);return ownedGearRefs().filter(r=>gearByName(r)?.name===ware.name).length===2&&!hallBattleProgress().purchasedShopStages.includes(51)&&glimmerArtifactWares().length===10;})()`);
check('Unique effects apply when equipped', `(()=>{const ref=ownedGearRefs().find(r=>gearByName(r)?.name==='Courtesy Engine');baseJobs.Verseborn.gear.ring=ref;return effectValue('Verseborn','openingTurnProgress')>=.25&&effectValue('Verseborn','statusChance')>=.2;})()`);
check('Shop row includes rarity, effect, affixes and price', `(()=>{const w=glimmerArtifactWares()[0],html=shopWareRowHtml(w,50);return html.includes('ARTIFACT')&&html.includes('First Courtesy')&&html.includes('Quickstart')&&html.includes('10000 G')&&html.includes('data-buy');})()`);
console.log('PASS 12/12 Glimmer Artifact shop checks');
